# Copyright (c) 2016 Open Connectivity Foundation (OCF) and AllJoyn Open
#    Source Project (AJOSP) Contributors and others.
#
#    SPDX-License-Identifier: Apache-2.0
#
#    All rights reserved. This program and the accompanying materials are
#    made available under the terms of the Apache License, Version 2.0
#    which accompanies this distribution, and is available at
#    http://www.apache.org/licenses/LICENSE-2.0
#
#    Copyright 2016 Open Connectivity Foundation and Contributors to
#    AllSeen Alliance. All rights reserved.
#
#    Permission to use, copy, modify, and/or distribute this software for
#    any purpose with or without fee is hereby granted, provided that the
#    above copyright notice and this permission notice appear in all
#    copies.
#
#     THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL
#     WARRANTIES WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED
#     WARRANTIES OF MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE
#     AUTHOR BE LIABLE FOR ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL
#     DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR
#     PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER
#     TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR
#     PERFORMANCE OF THIS SOFTWARE.

Import('cdm_env')

srcs = []
for component in ('common', 'controllee', 'controller'):
    srcs += cdm_env.Glob('%s/operation/*.cc' % component)
    srcs += cdm_env.Glob('%s/environment/*.cc' % component)
    srcs += cdm_env.Glob('%s/input/*.cc' % component)
    srcs += cdm_env.Glob('%s/userinterfacesettings/*.cc' % component)

srcs += cdm_env.Glob('*.cc')

cdm_env.Append(CPPPATH = '.');

# Platform specific sources
if cdm_env['OS'] == 'android':
    srcs += cdm_env.Glob('$OS/*.cc')
else:
    srcs += cdm_env.Glob('$OS_GROUP/*.cc')

libs = []

# Static library
objs = cdm_env.Object(srcs)
libs.append(cdm_env.StaticLibrary('alljoyn_cdm_interfaces', objs))

# Shared library
if cdm_env.get('LIBTYPE', 'static') != 'static':
    shobjs = cdm_env.SharedObject(srcs)
    libs.append(cdm_env.SharedLibrary('alljoyn_cdm_interfaces', shobjs))

Return('libs')