# # 
#    Copyright (c) 2016 Open Connectivity Foundation and AllJoyn Open
#    Source Project Contributors and others.
#    
#    All rights reserved. This program and the accompanying materials are
#    made available under the terms of the Apache License, Version 2.0
#    which accompanies this distribution, and is available at
#    http://www.apache.org/licenses/LICENSE-2.0


Import('cdm_env')

# Sources
srcs = cdm_env.Glob('*.cc')
srcs += cdm_env.Glob('interfaces/*.cc')
srcs += cdm_env.Glob('interfaces/operation/*.cc')
srcs += cdm_env.Glob('interfaces/environment/*.cc')
srcs += cdm_env.Glob('interfaces/input/*.cc')
srcs += cdm_env.Glob('interfaces/userinterfacesettings/*.cc')
cdm_env.Append(CPPPATH = '.');

# Platform specific sources
if cdm_env['OS'] == 'android':
    srcs += cdm_env.Glob('$OS/*.cc')
else:
    srcs += cdm_env.Glob('$OS_GROUP/*.cc')

libs = []

# Static library
objs = cdm_env.Object(srcs)
libs.append(cdm_env.StaticLibrary('alljoyn_cdm', objs))

# Shared library
if cdm_env.get('LIBTYPE', 'static') != 'static':
    shobjs = cdm_env.SharedObject(srcs)
    libs.append(cdm_env.SharedLibrary('alljoyn_cdm', shobjs))

Return('libs')