/******************************************************************************
 *  * Copyright (c) Open Connectivity Foundation (OCF) and AllJoyn Open
 *    Source Project (AJOSP) Contributors and others.
 *
 *    SPDX-License-Identifier: Apache-2.0
 *
 *    All rights reserved. This program and the accompanying materials are
 *    made available under the terms of the Apache License, Version 2.0
 *    which accompanies this distribution, and is available at
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 *    Copyright (c) Open Connectivity Foundation and Contributors to AllSeen
 *    Alliance. All rights reserved.
 *
 *    Permission to use, copy, modify, and/or distribute this software for
 *    any purpose with or without fee is hereby granted, provided that the
 *    above copyright notice and this permission notice appear in all
 *    copies.
 *
 *     THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL
 *     WARRANTIES WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED
 *     WARRANTIES OF MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE
 *     AUTHOR BE LIABLE FOR ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL
 *     DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR
 *     PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER
 *     TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR
 *     PERFORMANCE OF THIS SOFTWARE.
 ******************************************************************************/

// This file is automatically generated. Do not edit it.

#include <alljoyn/cdm/common/LogModule.h>
#include <alljoyn/cdm/common/CdmTypes.h>
#include <alljoyn/cdm/controller/InterfaceController.h>
#include <interfaces/controller/userinterfacesettings/LanguageDisplayIntfControllerListener.h>
#include <interfaces/controller/userinterfacesettings/LanguageDisplayIntfController.h>

using namespace qcc;
using namespace std;

namespace ajn {
namespace services {
//======================================================================

typedef Ref<LanguageDisplayIntfControllerListener> MyInterfaceListener;


class LanguageDisplayIntfController::Impl : public InterfaceController
{
  public:

    Impl(
        LanguageDisplayIntfController& outer,
        BusAttachment& busAttachment,
        MyInterfaceListener listener,
        Ref<ProxyBusObject> proxyBusObject
        )
      : InterfaceController(proxyBusObject),
        m_outer(outer),
        m_busAttachment(busAttachment),
        m_interfaceListener(listener)
    {
    }

    QStatus Init();

    const char* GetInterfaceName() const
    {
        return m_outer.GetInterfaceName().c_str();
    }

    QStatus GetDisplayLanguage(void* context);
    QStatus SetDisplayLanguage(const qcc::String& value, void* context);
    QStatus GetSupportedDisplayLanguages(void* context);


    void PropertiesChanged(ProxyBusObject& obj, const char* ifaceName, const MsgArg& changed, const MsgArg& invalidated, void* context);

    void GetDisplayLanguagePropertyCB(QStatus status, ProxyBusObject* obj, const MsgArg& value, void* context);
    void SetDisplayLanguagePropertyCB(QStatus status, ProxyBusObject* obj, void* context);
    void GetSupportedDisplayLanguagesPropertyCB(QStatus status, ProxyBusObject* obj, const MsgArg& value, void* context);



    // The outer facet
    LanguageDisplayIntfController& m_outer;

    // and inherit m_proxyObject from InterfaceController
    BusAttachment& m_busAttachment;
    MyInterfaceListener m_interfaceListener;
};

//======================================================================

QStatus LanguageDisplayIntfController::Impl::Init()
{
    auto status = m_proxyObject->RegisterPropertiesChangedListener(GetInterfaceName(), NULL, 0, *this, NULL);

    if (ER_OK != status) {
        QCC_LogError(status, ("%s: RegisterPropertiesChangedListener failed.", __func__));
    }

    const InterfaceDescription* intf = m_outer.GetInterfaceDescription();
    if (intf) {
    } else {
        status = ER_FAIL;
        QCC_LogError(status, ("%s: The interface description does not exist.", __func__));
    }

    return status;
}




QStatus LanguageDisplayIntfController::Impl::GetDisplayLanguage(void* context)
{
    auto status = m_proxyObject->GetPropertyAsync(GetInterfaceName(), s_prop_DisplayLanguage.c_str(), this,
                (ProxyBusObject::Listener::GetPropertyCB)&LanguageDisplayIntfController::Impl::GetDisplayLanguagePropertyCB, context);
    return status;
}

QStatus LanguageDisplayIntfController::Impl::SetDisplayLanguage(const qcc::String& value, void* context)
{
    MsgArg arg;
    {
        CdmMsgCvt<qcc::String> converter;
        converter.set(arg, value);
    }

    auto status = m_proxyObject->SetPropertyAsync(GetInterfaceName(), s_prop_DisplayLanguage.c_str(), arg, this,
                (ProxyBusObject::Listener::SetPropertyCB)&LanguageDisplayIntfController::Impl::SetDisplayLanguagePropertyCB, context);
    return status;
}

QStatus LanguageDisplayIntfController::Impl::GetSupportedDisplayLanguages(void* context)
{
    auto status = m_proxyObject->GetPropertyAsync(GetInterfaceName(), s_prop_SupportedDisplayLanguages.c_str(), this,
                (ProxyBusObject::Listener::GetPropertyCB)&LanguageDisplayIntfController::Impl::GetSupportedDisplayLanguagesPropertyCB, context);
    return status;
}





void LanguageDisplayIntfController::Impl::PropertiesChanged(ProxyBusObject& obj, const char* ifaceName, const MsgArg& changed, const MsgArg& invalidated, void* context)
{
    MsgArg* entries;
    size_t numEntries;

    changed.Get("a{sv}", &numEntries, &entries);
    for (size_t i = 0; i < numEntries; ++i) {
        const char* propName;
        MsgArg* propValue;
        entries[i].Get("{sv}", &propName, &propValue);
        String propNameStr(propName);

        if (s_prop_DisplayLanguage == propNameStr) {
            qcc::String val;
            {
                CdmMsgCvt<qcc::String> converter;
                converter.get((*propValue), val);
            }
            m_interfaceListener->OnDisplayLanguageChanged(obj.GetPath(), val);
        } else if (s_prop_SupportedDisplayLanguages == propNameStr) {
            std::vector<qcc::String> val;
            {
                CdmMsgCvt<std::vector<qcc::String>> converter;
                converter.get((*propValue), val);
            }
            m_interfaceListener->OnSupportedDisplayLanguagesChanged(obj.GetPath(), val);
        } else {
            QCC_DbgTrace(("Unknown property change signal received"));
        }
    }
}

//======================================================================
// Callbacks


void LanguageDisplayIntfController::Impl::GetDisplayLanguagePropertyCB(QStatus status, ProxyBusObject* obj, const MsgArg& value, void* context)
{
    if (obj) {
        qcc::String val;
        {
            CdmMsgCvt<qcc::String> converter;
            converter.get(value, val);
        }
        if (_QCC_DbgPrintCheck(DBG_GEN_MESSAGE, QCC_MODULE)) {
            auto s = CdmMsgCvt<qcc::String>().str(value);
            QCC_DbgPrintf(("%s: received property %s=%s", __func__, "DisplayLanguage", s.c_str()));
        }
        m_interfaceListener->OnResponseGetDisplayLanguage(status, obj->GetPath(), val, context);
    }
}



void LanguageDisplayIntfController::Impl::SetDisplayLanguagePropertyCB(QStatus status, ProxyBusObject* obj, void* context)
{
    QCC_DbgPrintf(("%s: set completed", __func__));
    if (obj) {
        m_interfaceListener->OnResponseSetDisplayLanguage(status, obj->GetPath(), context);
    }
}

void LanguageDisplayIntfController::Impl::GetSupportedDisplayLanguagesPropertyCB(QStatus status, ProxyBusObject* obj, const MsgArg& value, void* context)
{
    if (obj) {
        std::vector<qcc::String> val;
        {
            CdmMsgCvt<std::vector<qcc::String>> converter;
            converter.get(value, val);
        }
        if (_QCC_DbgPrintCheck(DBG_GEN_MESSAGE, QCC_MODULE)) {
            auto s = CdmMsgCvt<std::vector<qcc::String>>().str(value);
            QCC_DbgPrintf(("%s: received property %s=%s", __func__, "SupportedDisplayLanguages", s.c_str()));
        }
        m_interfaceListener->OnResponseGetSupportedDisplayLanguages(status, obj->GetPath(), val, context);
    }
}




//======================================================================
// Forward to the impl

LanguageDisplayIntfController::LanguageDisplayIntfController(
    BusAttachment& busAttachment,
    Ref<InterfaceControllerListener> listener,
    Ref<ProxyBusObject> cdmProxyObject
    )
  : m_impl(new Impl(*this, busAttachment, dynamic_pointer_cast<LanguageDisplayIntfControllerListener>(listener), cdmProxyObject))
{
}



LanguageDisplayIntfController::~LanguageDisplayIntfController()
{
    delete m_impl;
}



Ref<CdmInterface> LanguageDisplayIntfController::CreateInterface(BusAttachment& busAttachment, Ref<InterfaceControllerListener> listener, Ref<ProxyBusObject> cdmProxyObject)
{
    return mkRef<LanguageDisplayIntfController>(busAttachment, dynamic_pointer_cast<LanguageDisplayIntfControllerListener>(listener), cdmProxyObject);
}



QStatus LanguageDisplayIntfController::Init()
{
    // Call the superclass Init
    QStatus status = CdmInterface::Init();
    if (ER_OK != status) {
        QCC_LogError(status, ("%s: Interface init failed.", __func__));
        return status;
    }

    return m_impl->Init();
}



BusAttachment& LanguageDisplayIntfController::GetBusAttachment() const
{
    return m_impl->m_busAttachment;
}



QStatus LanguageDisplayIntfController::GetDisplayLanguage(void* context)
{
    return m_impl->GetDisplayLanguage(context);
}



QStatus LanguageDisplayIntfController::SetDisplayLanguage(const qcc::String& value, void* context)
{
    return m_impl->SetDisplayLanguage(value, context);
}



QStatus LanguageDisplayIntfController::GetSupportedDisplayLanguages(void* context)
{
    return m_impl->GetSupportedDisplayLanguages(context);
}

//======================================================================
} //namespace services
} //namespace ajn