/******************************************************************************
 * Copyright (c) 2016 Open Connectivity Foundation (OCF) and AllJoyn Open
 *    Source Project (AJOSP) Contributors and others.
 *
 *    SPDX-License-Identifier: Apache-2.0
 *
 *    All rights reserved. This program and the accompanying materials are
 *    made available under the terms of the Apache License, Version 2.0
 *    which accompanies this distribution, and is available at
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 *    Copyright 2016 Open Connectivity Foundation and Contributors to
 *    AllSeen Alliance. All rights reserved.
 *
 *    Permission to use, copy, modify, and/or distribute this software for
 *    any purpose with or without fee is hereby granted, provided that the
 *    above copyright notice and this permission notice appear in all
 *    copies.
 *
 *     THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL
 *     WARRANTIES WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED
 *     WARRANTIES OF MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE
 *     AUTHOR BE LIABLE FOR ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL
 *     DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR
 *     PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER
 *     TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR
 *     PERFORMANCE OF THIS SOFTWARE.
 ******************************************************************************/

// This file is automatically generated. Do not edit it.

#include <alljoyn/cdm/common/LogModule.h>
#include <alljoyn/cdm/common/CdmTypes.h>
#include <alljoyn/cdm/controller/InterfaceController.h>
#include <interfaces/controller/environment/TargetTemperatureIntfControllerListener.h>
#include <interfaces/controller/environment/TargetTemperatureIntfController.h>

using namespace qcc;
using namespace std;

namespace ajn {
namespace services {
//======================================================================

typedef Ref<TargetTemperatureIntfControllerListener> MyInterfaceListener;


class TargetTemperatureIntfController::Impl : public InterfaceController
{
  public:

    Impl(
        TargetTemperatureIntfController& outer,
        BusAttachment& busAttachment,
        MyInterfaceListener listener,
        Ref<ProxyBusObject> proxyBusObject
        )
      : InterfaceController(proxyBusObject),
        m_outer(outer),
        m_busAttachment(busAttachment),
        m_interfaceListener(listener)
    {
    }

    QStatus Init();

    const char* GetInterfaceName() const
    {
        return m_outer.GetInterfaceName().c_str();
    }

    QStatus GetTargetValue(void* context);
    QStatus SetTargetValue(const double value, void* context);
    QStatus GetMinValue(void* context);
    QStatus GetMaxValue(void* context);
    QStatus GetStepValue(void* context);


    void PropertiesChanged(ProxyBusObject& obj, const char* ifaceName, const MsgArg& changed, const MsgArg& invalidated, void* context);

    void GetTargetValuePropertyCB(QStatus status, ProxyBusObject* obj, const MsgArg& value, void* context);
    void SetTargetValuePropertyCB(QStatus status, ProxyBusObject* obj, void* context);
    void GetMinValuePropertyCB(QStatus status, ProxyBusObject* obj, const MsgArg& value, void* context);
    void GetMaxValuePropertyCB(QStatus status, ProxyBusObject* obj, const MsgArg& value, void* context);
    void GetStepValuePropertyCB(QStatus status, ProxyBusObject* obj, const MsgArg& value, void* context);



    // The outer facet
    TargetTemperatureIntfController& m_outer;

    // and inherit m_proxyObject from InterfaceController
    BusAttachment& m_busAttachment;
    MyInterfaceListener m_interfaceListener;
};

//======================================================================

QStatus TargetTemperatureIntfController::Impl::Init()
{
    auto status = m_proxyObject->RegisterPropertiesChangedListener(GetInterfaceName(), NULL, 0, *this, NULL);

    if (ER_OK != status) {
        QCC_LogError(status, ("%s: RegisterPropertiesChangedListener failed.", __func__));
    }

    const InterfaceDescription* intf = m_outer.GetInterfaceDescription();
    if (intf) {
    } else {
        status = ER_FAIL;
        QCC_LogError(status, ("%s: The interface description does not exist.", __func__));
    }

    return status;
}




QStatus TargetTemperatureIntfController::Impl::GetTargetValue(void* context)
{
    auto status = m_proxyObject->GetPropertyAsync(GetInterfaceName(), s_prop_TargetValue.c_str(), this,
                (ProxyBusObject::Listener::GetPropertyCB)&TargetTemperatureIntfController::Impl::GetTargetValuePropertyCB, context);
    return status;
}

QStatus TargetTemperatureIntfController::Impl::SetTargetValue(const double value, void* context)
{
    MsgArg arg;
    {
        CdmMsgCvt<double> converter;
        converter.set(arg, value);
    }

    auto status = m_proxyObject->SetPropertyAsync(GetInterfaceName(), s_prop_TargetValue.c_str(), arg, this,
                (ProxyBusObject::Listener::SetPropertyCB)&TargetTemperatureIntfController::Impl::SetTargetValuePropertyCB, context);
    return status;
}

QStatus TargetTemperatureIntfController::Impl::GetMinValue(void* context)
{
    auto status = m_proxyObject->GetPropertyAsync(GetInterfaceName(), s_prop_MinValue.c_str(), this,
                (ProxyBusObject::Listener::GetPropertyCB)&TargetTemperatureIntfController::Impl::GetMinValuePropertyCB, context);
    return status;
}

QStatus TargetTemperatureIntfController::Impl::GetMaxValue(void* context)
{
    auto status = m_proxyObject->GetPropertyAsync(GetInterfaceName(), s_prop_MaxValue.c_str(), this,
                (ProxyBusObject::Listener::GetPropertyCB)&TargetTemperatureIntfController::Impl::GetMaxValuePropertyCB, context);
    return status;
}

QStatus TargetTemperatureIntfController::Impl::GetStepValue(void* context)
{
    auto status = m_proxyObject->GetPropertyAsync(GetInterfaceName(), s_prop_StepValue.c_str(), this,
                (ProxyBusObject::Listener::GetPropertyCB)&TargetTemperatureIntfController::Impl::GetStepValuePropertyCB, context);
    return status;
}





void TargetTemperatureIntfController::Impl::PropertiesChanged(ProxyBusObject& obj, const char* ifaceName, const MsgArg& changed, const MsgArg& invalidated, void* context)
{
    MsgArg* entries;
    size_t numEntries;

    changed.Get("a{sv}", &numEntries, &entries);
    for (size_t i = 0; i < numEntries; ++i) {
        const char* propName;
        MsgArg* propValue;
        entries[i].Get("{sv}", &propName, &propValue);
        String propNameStr(propName);

        if (s_prop_TargetValue == propNameStr) {
            double val;
            {
                CdmMsgCvt<double> converter;
                converter.get((*propValue), val);
            }
            m_interfaceListener->OnTargetValueChanged(obj.GetPath(), val);
        } else if (s_prop_MinValue == propNameStr) {
            double val;
            {
                CdmMsgCvt<double> converter;
                converter.get((*propValue), val);
            }
            m_interfaceListener->OnMinValueChanged(obj.GetPath(), val);
        } else if (s_prop_MaxValue == propNameStr) {
            double val;
            {
                CdmMsgCvt<double> converter;
                converter.get((*propValue), val);
            }
            m_interfaceListener->OnMaxValueChanged(obj.GetPath(), val);
        } else if (s_prop_StepValue == propNameStr) {
            double val;
            {
                CdmMsgCvt<double> converter;
                converter.get((*propValue), val);
            }
            m_interfaceListener->OnStepValueChanged(obj.GetPath(), val);
        } else {
            QCC_DbgTrace(("Unknown property change signal received"));
        }
    }
}

//======================================================================
// Callbacks


void TargetTemperatureIntfController::Impl::GetTargetValuePropertyCB(QStatus status, ProxyBusObject* obj, const MsgArg& value, void* context)
{
    if (obj) {
        double val;
        {
            CdmMsgCvt<double> converter;
            converter.get(value, val);
        }
        if (_QCC_DbgPrintCheck(DBG_GEN_MESSAGE, QCC_MODULE)) {
            auto s = CdmMsgCvt<double>().str(value);
            QCC_DbgPrintf(("%s: received property %s=%s", __func__, "TargetValue", s.c_str()));
        }
        m_interfaceListener->OnResponseGetTargetValue(status, obj->GetPath(), val, context);
    }
}



void TargetTemperatureIntfController::Impl::SetTargetValuePropertyCB(QStatus status, ProxyBusObject* obj, void* context)
{
    QCC_DbgPrintf(("%s: set completed", __func__));
    if (obj) {
        m_interfaceListener->OnResponseSetTargetValue(status, obj->GetPath(), context);
    }
}

void TargetTemperatureIntfController::Impl::GetMinValuePropertyCB(QStatus status, ProxyBusObject* obj, const MsgArg& value, void* context)
{
    if (obj) {
        double val;
        {
            CdmMsgCvt<double> converter;
            converter.get(value, val);
        }
        if (_QCC_DbgPrintCheck(DBG_GEN_MESSAGE, QCC_MODULE)) {
            auto s = CdmMsgCvt<double>().str(value);
            QCC_DbgPrintf(("%s: received property %s=%s", __func__, "MinValue", s.c_str()));
        }
        m_interfaceListener->OnResponseGetMinValue(status, obj->GetPath(), val, context);
    }
}




void TargetTemperatureIntfController::Impl::GetMaxValuePropertyCB(QStatus status, ProxyBusObject* obj, const MsgArg& value, void* context)
{
    if (obj) {
        double val;
        {
            CdmMsgCvt<double> converter;
            converter.get(value, val);
        }
        if (_QCC_DbgPrintCheck(DBG_GEN_MESSAGE, QCC_MODULE)) {
            auto s = CdmMsgCvt<double>().str(value);
            QCC_DbgPrintf(("%s: received property %s=%s", __func__, "MaxValue", s.c_str()));
        }
        m_interfaceListener->OnResponseGetMaxValue(status, obj->GetPath(), val, context);
    }
}




void TargetTemperatureIntfController::Impl::GetStepValuePropertyCB(QStatus status, ProxyBusObject* obj, const MsgArg& value, void* context)
{
    if (obj) {
        double val;
        {
            CdmMsgCvt<double> converter;
            converter.get(value, val);
        }
        if (_QCC_DbgPrintCheck(DBG_GEN_MESSAGE, QCC_MODULE)) {
            auto s = CdmMsgCvt<double>().str(value);
            QCC_DbgPrintf(("%s: received property %s=%s", __func__, "StepValue", s.c_str()));
        }
        m_interfaceListener->OnResponseGetStepValue(status, obj->GetPath(), val, context);
    }
}




//======================================================================
// Forward to the impl

TargetTemperatureIntfController::TargetTemperatureIntfController(
    BusAttachment& busAttachment,
    Ref<InterfaceControllerListener> listener,
    Ref<ProxyBusObject> cdmProxyObject
    )
  : m_impl(new Impl(*this, busAttachment, dynamic_pointer_cast<TargetTemperatureIntfControllerListener>(listener), cdmProxyObject))
{
}



TargetTemperatureIntfController::~TargetTemperatureIntfController()
{
    delete m_impl;
}



Ref<CdmInterface> TargetTemperatureIntfController::CreateInterface(BusAttachment& busAttachment, Ref<InterfaceControllerListener> listener, Ref<ProxyBusObject> cdmProxyObject)
{
    return mkRef<TargetTemperatureIntfController>(busAttachment, dynamic_pointer_cast<TargetTemperatureIntfControllerListener>(listener), cdmProxyObject);
}



QStatus TargetTemperatureIntfController::Init()
{
    // Call the superclass Init
    QStatus status = CdmInterface::Init();
    if (ER_OK != status) {
        QCC_LogError(status, ("%s: Interface init failed.", __func__));
        return status;
    }

    return m_impl->Init();
}



BusAttachment& TargetTemperatureIntfController::GetBusAttachment() const
{
    return m_impl->m_busAttachment;
}



QStatus TargetTemperatureIntfController::GetTargetValue(void* context)
{
    return m_impl->GetTargetValue(context);
}



QStatus TargetTemperatureIntfController::SetTargetValue(const double value, void* context)
{
    return m_impl->SetTargetValue(value, context);
}



QStatus TargetTemperatureIntfController::GetMinValue(void* context)
{
    return m_impl->GetMinValue(context);
}



QStatus TargetTemperatureIntfController::GetMaxValue(void* context)
{
    return m_impl->GetMaxValue(context);
}



QStatus TargetTemperatureIntfController::GetStepValue(void* context)
{
    return m_impl->GetStepValue(context);
}

//======================================================================
} //namespace services
} //namespace ajn
