# Copyright AllSeen Alliance. All rights reserved.
#
#    Permission to use, copy, modify, and/or distribute this software for any
#    purpose with or without fee is hereby granted, provided that the above
#    copyright notice and this permission notice appear in all copies.
#
#    THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
#    WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
#    MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
#    ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
#    WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
#    ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
#    OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.

Import('hae_env')

local_env = hae_env.Clone()

local_env.Prepend(LIBS = ['alljoyn_hae', 'alljoyn_about' ])

if local_env['BR'] == 'on':
    # Build apps with bundled daemon support
    local_env.Prepend(LIBS = [local_env['ajrlib']])

if local_env.get('UINPUT') == 'on':
	# Add uinput integration in samples
    local_env.Prepend(CPPDEFINES = [ 'UINPUT' ])

# Sample programs

sample_dirs = [
    'IntegratedController',
    'IntegratedControllee',
    'TvControllee',
    'VDIControllee',
    'ACControllee',
    'RobotCleanerControllee',
    'CookTopControllee',
    'LaundryControllee'
    ]

exports = { 'env': local_env }

progs = [ local_env.SConscript('%s/SConscript' % sampleapp, exports = exports) for sampleapp in sample_dirs ]

Return('progs')

