# # 
#    Copyright (c) 2016 Open Connectivity Foundation and AllJoyn Open
#    Source Project Contributors and others.
#    
#    All rights reserved. This program and the accompanying materials are
#    made available under the terms of the Apache License, Version 2.0
#    which accompanies this distribution, and is available at
#    http://www.apache.org/licenses/LICENSE-2.0


Import('cdm_env')

local_env = cdm_env.Clone()

local_env.Prepend(LIBS = ['alljoyn_cdm', 'alljoyn_about' ])

if local_env['BR'] == 'on':
    # Build apps with bundled daemon support
    local_env.Prepend(LIBS = [local_env['ajrlib']])

if local_env.get('UINPUT') == 'on':
    # Add uinput integration in samples
    local_env.Prepend(CPPDEFINES = [ 'UINPUT' ])

# Sample programs

sample_dirs = [
    'IntegratedController',
    'IntegratedControllee',
    'TvControllee',
    'VDIControllee',
    'ACControllee',
    'RobotCleanerControllee',
    'CookTopControllee',
    'LaundryControllee',
    'TimerSimulator',
    'DeviceEmulator'
    ]

exports = { 'env': local_env }

progs = [ local_env.SConscript('%s/SConscript' % sampleapp, exports = exports) for sampleapp in sample_dirs ]

Return('progs')
