/******************************************************************************
 * Copyright (c) 2016 Open Connectivity Foundation (OCF) and AllJoyn Open
 *    Source Project (AJOSP) Contributors and others.
 *
 *    SPDX-License-Identifier: Apache-2.0
 *
 *    All rights reserved. This program and the accompanying materials are
 *    made available under the terms of the Apache License, Version 2.0
 *    which accompanies this distribution, and is available at
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 *    Copyright 2016 Open Connectivity Foundation and Contributors to
 *    AllSeen Alliance. All rights reserved.
 *
 *    Permission to use, copy, modify, and/or distribute this software for
 *    any purpose with or without fee is hereby granted, provided that the
 *    above copyright notice and this permission notice appear in all
 *    copies.
 *
 *     THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL
 *     WARRANTIES WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED
 *     WARRANTIES OF MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE
 *     AUTHOR BE LIABLE FOR ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL
 *     DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR
 *     PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER
 *     TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR
 *     PERFORMANCE OF THIS SOFTWARE.
 ******************************************************************************/

// This file is automatically generated. Do not edit it.

#include <alljoyn/BusAttachment.h>

#include <alljoyn/cdm/common/LogModule.h>
#include <alljoyn/cdm/util/CdmMsgCvt.h>

#include <alljoyn/cdm/controllee/CdmBusObject.h>
#include <alljoyn/cdm/controllee/InterfaceReceiver.h>
#include <alljoyn/cdm/controllee/InterfaceControlleeModel.h>

#include "WarpCoreIntfControllee.h"
#include "WarpCoreIntfControlleeModel.h"

#include <interfaces/controllee/CdmInterfaceValidation.h>


using namespace qcc;
using namespace std;

namespace ajn {
namespace services {

/**
 * WarpCore Interface Controllee implementation class
 */
class WarpCoreIntfControllee::Impl :
    public InterfaceReceiver,
    public WarpCoreInterface
{

  public:
    static Impl* CreateInterface(BusAttachment& busAttachment, Ref<WarpCoreIntfControlleeModel> model, CdmBusObject& cdmBusObject, CdmControllee& cdmControllee);

    /**
     * Initialize interface
     * @return status
     */
    QStatus Init() override;

    /**
     * override the interfaces GetInterfaceName method
     * @return
     */
    const qcc::String& GetInterfaceName() const override { return InterfaceName; }

    /**
     * a callback function for getting property.
     * @param[in] propName   Identifies the property to get
     * @param[out] val   Returns the property value. The type of this value is the actual value type.
     * @return status
     */
    QStatus OnGetProperty(const qcc::String& propName, MsgArg& val) override;

    /**
     * a callback function for setting property.
     * @param[in] propName  Identifies the property to set
     * @param[in] val       The property value to set. The type of this value is the actual value type.
     */
    QStatus OnSetProperty(const qcc::String& propName, MsgArg& val) override;

    /**
     * method handler
     * @param[in] member    Method interface member entry.
     * @param[in] message   The received method call message.
     */
    void OnMethodHandler(const InterfaceDescription::Member* member, Message& msg) override;

    /**
     * Get method handlers
     * @return MethodHandlers
     */
    const MethodHandlers& GetMethodHanders() const override { return m_methodHandlers; }

    /**
     * Get bus attachment
     * @return bus attachment
     */
    BusAttachment& GetBusAttachment() const override { return m_busAttachment; }

    /**
     * Emits a changed signal for the WarpFactor property
     * @param[in] newValue new value of warp factor
     * @return ER_OK on success
     */
    QStatus EmitWarpFactorChanged(const double newValue);

    /**
     * Emits a changed signal for the CurrentWarpFactor property
     * @param[in] newValue new value of current warp factor
     * @return ER_OK on success
     */
    QStatus EmitCurrentWarpFactorChanged(const double newValue);

    /**
     * Emits a changed signal for the IsEngaged property
     * @param[in] newValue new value of is engaged
     * @return ER_OK on success
     */
    QStatus EmitIsEngagedChanged(const bool newValue);

    /**
     * Handler of Engage method
     * @param member
     * @param msg reference of alljoyn Message
     */
    void OnEngage(const InterfaceDescription::Member* member, Message& msg);

    /**
     * Handler of Disengage method
     * @param member
     * @param msg reference of alljoyn Message
     */
    void OnDisengage(const InterfaceDescription::Member* member, Message& msg);

  private:
    /**
     * Constructor of WarpCoreIntfControllee::Impl
     */
    Impl(BusAttachment& busAttachment, Ref<WarpCoreIntfControlleeModel> model, CdmBusObject& cdmBusObject, CdmControllee& cdmControllee);

    QStatus clampWarpFactor(double value, double& out);

    BusAttachment& m_busAttachment;
    CdmControllee& m_cdmControllee;
    MethodHandlers m_methodHandlers;

    Ref<WarpCoreIntfControlleeModel> m_WarpCoreModelInterface;
    qcc::String InterfaceName;
};

/*
 * Forwarding
 */
WarpCoreIntfControllee::WarpCoreIntfControllee(BusAttachment& busAttachment, Ref<InterfaceControlleeModel> model, CdmBusObject& cdmBusObject, CdmControllee& cdmControllee)
    : m_impl(Impl::CreateInterface(busAttachment, dynamic_pointer_cast<WarpCoreIntfControlleeModel>(model), cdmBusObject, cdmControllee))
{}


WarpCoreIntfControllee::~WarpCoreIntfControllee()
{
    delete m_impl;
}

const qcc::String& WarpCoreIntfControllee::GetInterfaceName() const
{
    return m_impl->GetInterfaceName();
}

QStatus WarpCoreIntfControllee::EmitWarpFactorChanged(const double newValue)
{
    return (m_impl == nullptr) ? ER_FAIL : m_impl->EmitWarpFactorChanged(newValue);
}

QStatus WarpCoreIntfControllee::EmitCurrentWarpFactorChanged(const double newValue)
{
    return (m_impl == nullptr) ? ER_FAIL : m_impl->EmitCurrentWarpFactorChanged(newValue);
}

QStatus WarpCoreIntfControllee::EmitIsEngagedChanged(const bool newValue)
{
    return (m_impl == nullptr) ? ER_FAIL : m_impl->EmitIsEngagedChanged(newValue);
}


/*
 * Implementation
 */
 WarpCoreIntfControllee::Impl* WarpCoreIntfControllee::Impl::CreateInterface(
    BusAttachment& busAttachment,
    Ref<WarpCoreIntfControlleeModel> model,
    CdmBusObject& cdmBusObject,
    CdmControllee& cdmControllee)
{
    WarpCoreIntfControllee::Impl* interface = new WarpCoreIntfControllee::Impl(busAttachment, model, cdmBusObject, cdmControllee);

    QStatus status = interface->Init();
    if (status != ER_OK) {
        QCC_LogError(status, ("%s: could not initialize interface", __func__));
        goto ERROR_CLEANUP;
    }

    status = cdmBusObject.RegisterInterface(interface);
    if (status != ER_OK) {
        goto ERROR_CLEANUP;
    }

    return interface;

ERROR_CLEANUP:
    delete interface;
    return nullptr;
}

WarpCoreIntfControllee::Impl::Impl(BusAttachment& busAttachment, Ref<WarpCoreIntfControlleeModel> model, CdmBusObject& cdmBusObject, CdmControllee& cdmControllee) :
    InterfaceReceiver(cdmBusObject),
    m_busAttachment(busAttachment),
    m_cdmControllee(cdmControllee),
    m_methodHandlers(),
    m_WarpCoreModelInterface(model),
    InterfaceName(WarpCoreInterface::INTERFACE_NAME)
{
    ignore_unused(m_cdmControllee);
}


QStatus WarpCoreIntfControllee::Impl::Init()
{
    QStatus status = CdmInterface::Init();

    const InterfaceDescription::Member* EngageMember = m_interfaceDescription->GetMember(s_method_Engage.c_str());
    InterfaceReceiver::CdmMethodHandler EngageHandler = static_cast<InterfaceReceiver::CdmMethodHandler>(&Impl::OnEngage);

    m_methodHandlers.push_back(make_pair(EngageMember, EngageHandler));

    const InterfaceDescription::Member* DisengageMember = m_interfaceDescription->GetMember(s_method_Disengage.c_str());
    InterfaceReceiver::CdmMethodHandler DisengageHandler = static_cast<InterfaceReceiver::CdmMethodHandler>(&Impl::OnDisengage);

    m_methodHandlers.push_back(make_pair(DisengageMember, DisengageHandler));

    return status;
}

QStatus WarpCoreIntfControllee::Impl::OnGetProperty(const String& propName, MsgArg& msgarg)
{
    if (!(s_prop_Version.compare(propName))) {
        msgarg.typeId = ALLJOYN_UINT16;
        msgarg.v_uint16 = GetInterfaceVersion();
        return ER_OK;
    } else {
        if (!(s_prop_WarpFactor.compare(propName))) {
            double value;
            auto status = m_WarpCoreModelInterface->GetWarpFactor(value);
            if (status != ER_OK) {
                QCC_LogError(status, ("%s: failed to get actual property value from application. use previous value.", __func__));
                return ER_FAIL;
            }

            {
                CdmMsgCvt<double> converter;
                converter.set(msgarg, value);
            }
            return ER_OK;
        } else        if (!(s_prop_CurrentWarpFactor.compare(propName))) {
            double value;
            auto status = m_WarpCoreModelInterface->GetCurrentWarpFactor(value);
            if (status != ER_OK) {
                QCC_LogError(status, ("%s: failed to get actual property value from application. use previous value.", __func__));
                return ER_FAIL;
            }

            {
                CdmMsgCvt<double> converter;
                converter.set(msgarg, value);
            }
            return ER_OK;
        } else        if (!(s_prop_IsEngaged.compare(propName))) {
            bool value;
            auto status = m_WarpCoreModelInterface->GetIsEngaged(value);
            if (status != ER_OK) {
                QCC_LogError(status, ("%s: failed to get actual property value from application. use previous value.", __func__));
                return ER_FAIL;
            }

            {
                CdmMsgCvt<bool> converter;
                converter.set(msgarg, value);
            }
            return ER_OK;
        } else {
            return ER_BUS_NO_SUCH_PROPERTY;
        }
    }
}

QStatus WarpCoreIntfControllee::Impl::OnSetProperty(const String& propName, MsgArg& msgarg)
{
    if (!(s_prop_WarpFactor.compare(propName))) {
        if (msgarg.Signature() != "d") {
            return ER_BUS_NO_SUCH_PROPERTY;
        }
        double value;
        {
            CdmMsgCvt<double> converter;
            converter.get(msgarg, value);
        }

        double validValue = value;

        if (clampWarpFactor(value, validValue) != ER_OK)
            return ER_INVALID_DATA;

        QStatus status = m_WarpCoreModelInterface->SetWarpFactor(validValue);
        if (status != ER_OK) {
            QCC_LogError(status, ("%s: failed to set property value", __func__));
            return ER_BUS_PROPERTY_VALUE_NOT_SET;
        }

        if (m_cdmControllee.EmitChangedSignalOnSetProperty())
            EmitWarpFactorChanged(validValue);

        return ER_OK;
    } else    if (!(s_prop_CurrentWarpFactor.compare(propName))) {
        if (msgarg.Signature() != "d") {
            return ER_BUS_NO_SUCH_PROPERTY;
        }
        return ER_BUS_PROPERTY_VALUE_NOT_SET;
    } else    if (!(s_prop_IsEngaged.compare(propName))) {
        if (msgarg.Signature() != "b") {
            return ER_BUS_NO_SUCH_PROPERTY;
        }
        return ER_BUS_PROPERTY_VALUE_NOT_SET;
    } else {
        return ER_BUS_NO_SUCH_PROPERTY;
    }
}

void WarpCoreIntfControllee::Impl::OnMethodHandler(const InterfaceDescription::Member* member, Message& msg)
{
    bool isFound = false;
    MethodHandlers::const_iterator it;
    for (it = m_methodHandlers.begin(); it != m_methodHandlers.end(); ++it) {
        if (it->first == member) {
            InterfaceReceiver::CdmMethodHandler handler = it->second;
            (this->*handler)(member, msg);
            isFound = true;
            break;
        }
    }

    if (!isFound) {
        auto status = ER_BUS_METHOD_CALL_ABORTED;
        QCC_LogError(status, ("%s: could not find method handler.", __func__));
        m_busObject.ReplyMethodCall(msg, status);
    }
}

QStatus WarpCoreIntfControllee::Impl::EmitWarpFactorChanged(const double newValue)
{
    QStatus status = ER_OK;

    MsgArg val;
    {
        CdmMsgCvt<double> converter;
        converter.set(val, newValue);
    }
    m_busObject.EmitPropChanged(GetInterfaceName().c_str(), s_prop_WarpFactor.c_str(), val, SESSION_ID_ALL_HOSTED, ALLJOYN_FLAG_GLOBAL_BROADCAST);

    return status;
}

QStatus WarpCoreIntfControllee::Impl::EmitCurrentWarpFactorChanged(const double newValue)
{
    QStatus status = ER_OK;

    MsgArg val;
    {
        CdmMsgCvt<double> converter;
        converter.set(val, newValue);
    }
    m_busObject.EmitPropChanged(GetInterfaceName().c_str(), s_prop_CurrentWarpFactor.c_str(), val, SESSION_ID_ALL_HOSTED, ALLJOYN_FLAG_GLOBAL_BROADCAST);

    return status;
}

QStatus WarpCoreIntfControllee::Impl::EmitIsEngagedChanged(const bool newValue)
{
    QStatus status = ER_OK;

    MsgArg val;
    {
        CdmMsgCvt<bool> converter;
        converter.set(val, newValue);
    }
    m_busObject.EmitPropChanged(GetInterfaceName().c_str(), s_prop_IsEngaged.c_str(), val, SESSION_ID_ALL_HOSTED, ALLJOYN_FLAG_GLOBAL_BROADCAST);

    return status;
}

void WarpCoreIntfControllee::Impl::OnEngage(const InterfaceDescription::Member* member, Message& msg) {
    const MsgArg* args = NULL;
    size_t numArgs = 0;

    msg->GetArgs(numArgs, args);


    ErrorCode errorCode = NOT_ERROR;
    auto status = m_WarpCoreModelInterface->Engage(errorCode, m_cdmControllee);


    if (status == ER_OK) {
        m_busObject.ReplyMethodCall(msg, status);
    } else {
        if (errorCode == NOT_ERROR) {
            QCC_LogError(status, ("%s: status is not ER_OK, but errorCode was not set.", __func__));
            m_busObject.ReplyMethodCall(msg, status);
        } else {
                m_busObject.ReplyMethodCall(msg, CdmInterface::GetInterfaceErrorName(errorCode).c_str(),
                        CdmInterface::GetInterfaceErrorMessage(errorCode).c_str());
        }
    }
}
void WarpCoreIntfControllee::Impl::OnDisengage(const InterfaceDescription::Member* member, Message& msg) {
    const MsgArg* args = NULL;
    size_t numArgs = 0;

    msg->GetArgs(numArgs, args);


    ErrorCode errorCode = NOT_ERROR;
    auto status = m_WarpCoreModelInterface->Disengage(errorCode, m_cdmControllee);


    if (status == ER_OK) {
        m_busObject.ReplyMethodCall(msg, status);
    } else {
        if (errorCode == NOT_ERROR) {
            QCC_LogError(status, ("%s: status is not ER_OK, but errorCode was not set.", __func__));
            m_busObject.ReplyMethodCall(msg, status);
        } else {
                m_busObject.ReplyMethodCall(msg, CdmInterface::GetInterfaceErrorName(errorCode).c_str(),
                        CdmInterface::GetInterfaceErrorMessage(errorCode).c_str());
        }
    }
}

QStatus WarpCoreIntfControllee::Impl::clampWarpFactor(double value, double& out)
{

    double minValue = 1.0;

    double maxValue = 9.8;
    double stepValue = 0;

    out = clamp<double>(value, minValue, maxValue, stepValue);
    return ER_OK;
}

} //namespace services
} //namespace ajn
