/******************************************************************************
 * Copyright (c) 2016 Open Connectivity Foundation (OCF) and AllJoyn Open
 *    Source Project (AJOSP) Contributors and others.
 *
 *    SPDX-License-Identifier: Apache-2.0
 *
 *    All rights reserved. This program and the accompanying materials are
 *    made available under the terms of the Apache License, Version 2.0
 *    which accompanies this distribution, and is available at
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 *    Copyright 2016 Open Connectivity Foundation and Contributors to
 *    AllSeen Alliance. All rights reserved.
 *
 *    Permission to use, copy, modify, and/or distribute this software for
 *    any purpose with or without fee is hereby granted, provided that the
 *    above copyright notice and this permission notice appear in all
 *    copies.
 *
 *     THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL
 *     WARRANTIES WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED
 *     WARRANTIES OF MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE
 *     AUTHOR BE LIABLE FOR ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL
 *     DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR
 *     PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER
 *     TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR
 *     PERFORMANCE OF THIS SOFTWARE.
 ******************************************************************************/

// This file is automatically generated. Do not edit it.

#ifndef WARPCOREINTFCONTROLLERLISTENER_H_
#define WARPCOREINTFCONTROLLERLISTENER_H_

#include <qcc/String.h>
#include <alljoyn/Status.h>
#include <alljoyn/cdm/controller/InterfaceControllerListener.h>
#include "WarpCoreInterface.h"

namespace ajn {
namespace services {

/**
 * WarpCore Interface Controller Listener class
 */
class WarpCoreIntfControllerListener : public InterfaceControllerListener {
  public:

    /**
     * Destructor of WarpCoreIntfControllerListener
     */
    virtual ~WarpCoreIntfControllerListener() {}

    /**
     * Callback handler for GetWarpFactor completion
     * @param[in] status ER_OK on success
     * @param[in] objectPath the object path
     * @param[in] value The value of WarpFactor
     *                  (The desired warp factor.)
     * @param[in] context the context that is passed from application
     */
    virtual void OnResponseGetWarpFactor(QStatus status, const qcc::String& objectPath, const double value, void* context) {}

    /**
     * Handler for WarpFactor property changed
     * @param[in] objectPath the object path
     * @param[in] value The value of WarpFactor
     *                  (The desired warp factor.)
     */
    virtual void OnWarpFactorChanged(const qcc::String& objectPath, const double value) {}

    /**
     * Callback handler for SetWarpFactor completion
     * @param[in] status ER_OK on success
     * @param[in] objectPath the object path
     * @param[in] context the context that is passed from application
     */
    virtual void OnResponseSetWarpFactor(QStatus status, const qcc::String& objectPath, void* context) {}

    /**
     * Callback handler for GetCurrentWarpFactor completion
     * @param[in] status ER_OK on success
     * @param[in] objectPath the object path
     * @param[in] value The value of CurrentWarpFactor
     *                  (The current warp factor.)
     * @param[in] context the context that is passed from application
     */
    virtual void OnResponseGetCurrentWarpFactor(QStatus status, const qcc::String& objectPath, const double value, void* context) {}

    /**
     * Handler for CurrentWarpFactor property changed
     * @param[in] objectPath the object path
     * @param[in] value The value of CurrentWarpFactor
     *                  (The current warp factor.)
     */
    virtual void OnCurrentWarpFactorChanged(const qcc::String& objectPath, const double value) {}

    /**
     * Callback handler for GetIsEngaged completion
     * @param[in] status ER_OK on success
     * @param[in] objectPath the object path
     * @param[in] value The value of IsEngaged
     *                  (Current state of the warp core.)
     * @param[in] context the context that is passed from application
     */
    virtual void OnResponseGetIsEngaged(QStatus status, const qcc::String& objectPath, const bool value, void* context) {}

    /**
     * Handler for IsEngaged property changed
     * @param[in] objectPath the object path
     * @param[in] value The value of IsEngaged
     *                  (Current state of the warp core.)
     */
    virtual void OnIsEngagedChanged(const qcc::String& objectPath, const bool value) {}

    /**
     * Callback handler for Engage completion
     * @param[in] status ER_OK on success
     * @param[in] objectPath the object path
     * @param[in] context the context that is passed from application
     * @param[in] errorName the detail errorName is passed when the method call is failed
     * @param[in] errorMessage the errorMessage that describes the error
     */
    virtual void OnResponseEngage(QStatus status, const qcc::String& objectPath, void* context, const char* errorName, const char* errorMessage) {}

    /**
     * Callback handler for Disengage completion
     * @param[in] status ER_OK on success
     * @param[in] objectPath the object path
     * @param[in] context the context that is passed from application
     * @param[in] errorName the detail errorName is passed when the method call is failed
     * @param[in] errorMessage the errorMessage that describes the error
     */
    virtual void OnResponseDisengage(QStatus status, const qcc::String& objectPath, void* context, const char* errorName, const char* errorMessage) {}
};

} //namespace services
} //namespace ajn

#endif /* WARPCOREINTFCONTROLLERLISTENER_H_ */
