/******************************************************************************
 * Copyright (c) 2016 Open Connectivity Foundation (OCF) and AllJoyn Open
 *    Source Project (AJOSP) Contributors and others.
 *
 *    SPDX-License-Identifier: Apache-2.0
 *
 *    All rights reserved. This program and the accompanying materials are
 *    made available under the terms of the Apache License, Version 2.0
 *    which accompanies this distribution, and is available at
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 *    Copyright 2016 Open Connectivity Foundation and Contributors to
 *    AllSeen Alliance. All rights reserved.
 *
 *    Permission to use, copy, modify, and/or distribute this software for
 *    any purpose with or without fee is hereby granted, provided that the
 *    above copyright notice and this permission notice appear in all
 *    copies.
 *
 *     THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL
 *     WARRANTIES WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED
 *     WARRANTIES OF MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE
 *     AUTHOR BE LIABLE FOR ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL
 *     DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR
 *     PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER
 *     TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR
 *     PERFORMANCE OF THIS SOFTWARE.
 ******************************************************************************/

// This file is automatically generated. Do not edit it.

#include <alljoyn/cdm/common/LogModule.h>
#include <alljoyn/cdm/common/CdmTypes.h>
#include <alljoyn/cdm/controller/InterfaceController.h>
#include "WarpCoreIntfControllerListener.h"
#include "WarpCoreIntfController.h"

using namespace qcc;
using namespace std;

namespace ajn {
namespace services {
//======================================================================

typedef Ref<WarpCoreIntfControllerListener> MyInterfaceListener;


class WarpCoreIntfController::Impl : public InterfaceController
{
  public:

    Impl(
        WarpCoreIntfController& outer,
        BusAttachment& busAttachment,
        MyInterfaceListener listener,
        Ref<ProxyBusObject> proxyBusObject
        )
      : InterfaceController(proxyBusObject),
        m_outer(outer),
        m_busAttachment(busAttachment),
        m_interfaceListener(listener)
    {
    }

    QStatus Init();

    const char* GetInterfaceName() const
    {
        const char *name = INTERFACE_NAME;
        return name;
    }

    QStatus GetWarpFactor(void* context);
    QStatus SetWarpFactor(const double value, void* context);
    QStatus GetCurrentWarpFactor(void* context);
    QStatus GetIsEngaged(void* context);

    virtual QStatus Engage(void* context);
    virtual QStatus Disengage(void* context);

    void PropertiesChanged(ProxyBusObject& obj, const char* ifaceName, const MsgArg& changed, const MsgArg& invalidated, void* context);

    void GetWarpFactorPropertyCB(QStatus status, ProxyBusObject* obj, const MsgArg& value, void* context);
    void SetWarpFactorPropertyCB(QStatus status, ProxyBusObject* obj, void* context);
    void GetCurrentWarpFactorPropertyCB(QStatus status, ProxyBusObject* obj, const MsgArg& value, void* context);
    void GetIsEngagedPropertyCB(QStatus status, ProxyBusObject* obj, const MsgArg& value, void* context);

    void EngageReplyHandler(Message& message, void* context);
    void DisengageReplyHandler(Message& message, void* context);


    // The outer facet
    WarpCoreIntfController& m_outer;

    // and inherit m_proxyObject from InterfaceController
    BusAttachment& m_busAttachment;
    MyInterfaceListener m_interfaceListener;
};

//======================================================================

QStatus WarpCoreIntfController::Impl::Init()
{
    auto status = m_proxyObject->RegisterPropertiesChangedListener(GetInterfaceName(), NULL, 0, *this, NULL);

    if (ER_OK != status) {
        QCC_LogError(status, ("%s: RegisterPropertiesChangedListener failed.", __func__));
    }

    const InterfaceDescription* intf = m_outer.GetInterfaceDescription();
    if (intf) {
    } else {
        status = ER_FAIL;
        QCC_LogError(status, ("%s: The interface description does not exist.", __func__));
    }

    return status;
}




QStatus WarpCoreIntfController::Impl::GetWarpFactor(void* context)
{
    auto status = m_proxyObject->GetPropertyAsync(GetInterfaceName(), s_prop_WarpFactor.c_str(), this,
                (ProxyBusObject::Listener::GetPropertyCB)&WarpCoreIntfController::Impl::GetWarpFactorPropertyCB, context);
    return status;
}

QStatus WarpCoreIntfController::Impl::SetWarpFactor(const double value, void* context)
{
    MsgArg arg;
    {
        CdmMsgCvt<double> converter;
        converter.set(arg, value);
    }

    auto status = m_proxyObject->SetPropertyAsync(GetInterfaceName(), s_prop_WarpFactor.c_str(), arg, this,
                (ProxyBusObject::Listener::SetPropertyCB)&WarpCoreIntfController::Impl::SetWarpFactorPropertyCB, context);
    return status;
}

QStatus WarpCoreIntfController::Impl::GetCurrentWarpFactor(void* context)
{
    auto status = m_proxyObject->GetPropertyAsync(GetInterfaceName(), s_prop_CurrentWarpFactor.c_str(), this,
                (ProxyBusObject::Listener::GetPropertyCB)&WarpCoreIntfController::Impl::GetCurrentWarpFactorPropertyCB, context);
    return status;
}

QStatus WarpCoreIntfController::Impl::GetIsEngaged(void* context)
{
    auto status = m_proxyObject->GetPropertyAsync(GetInterfaceName(), s_prop_IsEngaged.c_str(), this,
                (ProxyBusObject::Listener::GetPropertyCB)&WarpCoreIntfController::Impl::GetIsEngagedPropertyCB, context);
    return status;
}



QStatus WarpCoreIntfController::Impl::Engage(void* context)
{
    // Method call
    static const size_t numInputs = 0;
    MsgArg* args = 0;

    auto status = m_proxyObject->MethodCallAsync(GetInterfaceName(), s_method_Engage.c_str(), this,
                (MessageReceiver::ReplyHandler)&WarpCoreIntfController::Impl::EngageReplyHandler,
                args, numInputs, context);
    return status;
}

QStatus WarpCoreIntfController::Impl::Disengage(void* context)
{
    // Method call
    static const size_t numInputs = 0;
    MsgArg* args = 0;

    auto status = m_proxyObject->MethodCallAsync(GetInterfaceName(), s_method_Disengage.c_str(), this,
                (MessageReceiver::ReplyHandler)&WarpCoreIntfController::Impl::DisengageReplyHandler,
                args, numInputs, context);
    return status;
}



void WarpCoreIntfController::Impl::PropertiesChanged(ProxyBusObject& obj, const char* ifaceName, const MsgArg& changed, const MsgArg& invalidated, void* context)
{
    MsgArg* entries;
    size_t numEntries;

    changed.Get("a{sv}", &numEntries, &entries);
    for (size_t i = 0; i < numEntries; ++i) {
        const char* propName;
        MsgArg* propValue;
        entries[i].Get("{sv}", &propName, &propValue);
        String propNameStr(propName);

        if (s_prop_WarpFactor == propNameStr) {
            double val;
            {
                CdmMsgCvt<double> converter;
                converter.get((*propValue), val);
            }
            m_interfaceListener->OnWarpFactorChanged(obj.GetPath(), val);
        } else if (s_prop_CurrentWarpFactor == propNameStr) {
            double val;
            {
                CdmMsgCvt<double> converter;
                converter.get((*propValue), val);
            }
            m_interfaceListener->OnCurrentWarpFactorChanged(obj.GetPath(), val);
        } else if (s_prop_IsEngaged == propNameStr) {
            bool val;
            {
                CdmMsgCvt<bool> converter;
                converter.get((*propValue), val);
            }
            m_interfaceListener->OnIsEngagedChanged(obj.GetPath(), val);
        } else {
            QCC_DbgTrace(("Unknown property change signal received"));
        }
    }
}

//======================================================================
// Callbacks


void WarpCoreIntfController::Impl::GetWarpFactorPropertyCB(QStatus status, ProxyBusObject* obj, const MsgArg& value, void* context)
{
    if (obj) {
        double val;
        {
            CdmMsgCvt<double> converter;
            converter.get(value, val);
        }
        if (_QCC_DbgPrintCheck(DBG_GEN_MESSAGE, QCC_MODULE)) {
            auto s = CdmMsgCvt<double>().str(value);
            QCC_DbgPrintf(("%s: received property %s=%s", __func__, "WarpFactor", s.c_str()));
        }
        m_interfaceListener->OnResponseGetWarpFactor(status, obj->GetPath(), val, context);
    }
}



void WarpCoreIntfController::Impl::SetWarpFactorPropertyCB(QStatus status, ProxyBusObject* obj, void* context)
{
    QCC_DbgPrintf(("%s: set completed", __func__));
    if (obj) {
        m_interfaceListener->OnResponseSetWarpFactor(status, obj->GetPath(), context);
    }
}

void WarpCoreIntfController::Impl::GetCurrentWarpFactorPropertyCB(QStatus status, ProxyBusObject* obj, const MsgArg& value, void* context)
{
    if (obj) {
        double val;
        {
            CdmMsgCvt<double> converter;
            converter.get(value, val);
        }
        if (_QCC_DbgPrintCheck(DBG_GEN_MESSAGE, QCC_MODULE)) {
            auto s = CdmMsgCvt<double>().str(value);
            QCC_DbgPrintf(("%s: received property %s=%s", __func__, "CurrentWarpFactor", s.c_str()));
        }
        m_interfaceListener->OnResponseGetCurrentWarpFactor(status, obj->GetPath(), val, context);
    }
}




void WarpCoreIntfController::Impl::GetIsEngagedPropertyCB(QStatus status, ProxyBusObject* obj, const MsgArg& value, void* context)
{
    if (obj) {
        bool val;
        {
            CdmMsgCvt<bool> converter;
            converter.get(value, val);
        }
        if (_QCC_DbgPrintCheck(DBG_GEN_MESSAGE, QCC_MODULE)) {
            auto s = CdmMsgCvt<bool>().str(value);
            QCC_DbgPrintf(("%s: received property %s=%s", __func__, "IsEngaged", s.c_str()));
        }
        m_interfaceListener->OnResponseGetIsEngaged(status, obj->GetPath(), val, context);
    }
}






void WarpCoreIntfController::Impl::EngageReplyHandler(Message& message, void* context)
{
    qcc::String errorMessage;
    const char* errorName = message->GetErrorName(&errorMessage);
    QStatus status = ER_OK;
    size_t numArgs = 0;
    const MsgArg* args = 0;


    if (message->GetType() == MESSAGE_METHOD_RET) {
        message->GetArgs(numArgs, args);
    } else {
        status = ER_FAIL;
    }

    m_interfaceListener->OnResponseEngage(status, m_proxyObject->GetPath(), context, errorName, errorMessage.c_str());
}



void WarpCoreIntfController::Impl::DisengageReplyHandler(Message& message, void* context)
{
    qcc::String errorMessage;
    const char* errorName = message->GetErrorName(&errorMessage);
    QStatus status = ER_OK;
    size_t numArgs = 0;
    const MsgArg* args = 0;


    if (message->GetType() == MESSAGE_METHOD_RET) {
        message->GetArgs(numArgs, args);
    } else {
        status = ER_FAIL;
    }

    m_interfaceListener->OnResponseDisengage(status, m_proxyObject->GetPath(), context, errorName, errorMessage.c_str());
}

//======================================================================
// Forward to the impl

WarpCoreIntfController::WarpCoreIntfController(
    BusAttachment& busAttachment,
    Ref<InterfaceControllerListener> listener,
    Ref<ProxyBusObject> cdmProxyObject
    )
  : m_impl(new Impl(*this, busAttachment, dynamic_pointer_cast<WarpCoreIntfControllerListener>(listener), cdmProxyObject))
{
}



WarpCoreIntfController::~WarpCoreIntfController()
{
    delete m_impl;
}



Ref<CdmInterface> WarpCoreIntfController::CreateInterface(BusAttachment& busAttachment, Ref<InterfaceControllerListener> listener, Ref<ProxyBusObject> cdmProxyObject)
{
    return mkRef<WarpCoreIntfController>(busAttachment, dynamic_pointer_cast<WarpCoreIntfControllerListener>(listener), cdmProxyObject);
}



QStatus WarpCoreIntfController::Init()
{
    // Call the superclass Init
    QStatus status = CdmInterface::Init(WarpCoreInterface::INTERFACE_NAME);
    if (ER_OK != status) {
        QCC_LogError(status, ("%s: Interface init failed.", __func__));
        return status;
    }

    return m_impl->Init();
}



BusAttachment& WarpCoreIntfController::GetBusAttachment() const
{
    return m_impl->m_busAttachment;
}



QStatus WarpCoreIntfController::GetWarpFactor(void* context)
{
    return m_impl->GetWarpFactor(context);
}



QStatus WarpCoreIntfController::SetWarpFactor(const double value, void* context)
{
    return m_impl->SetWarpFactor(value, context);
}



QStatus WarpCoreIntfController::GetCurrentWarpFactor(void* context)
{
    return m_impl->GetCurrentWarpFactor(context);
}



QStatus WarpCoreIntfController::GetIsEngaged(void* context)
{
    return m_impl->GetIsEngaged(context);
}



QStatus WarpCoreIntfController::Engage(void* context)
{
    return m_impl->Engage(context);
}



QStatus WarpCoreIntfController::Disengage(void* context)
{
    return m_impl->Disengage(context);
}

//======================================================================
} //namespace services
} //namespace ajn
