/******************************************************************************
 * Copyright (c) 2016 Open Connectivity Foundation (OCF) and AllJoyn Open
 *    Source Project (AJOSP) Contributors and others.
 *
 *    SPDX-License-Identifier: Apache-2.0
 *
 *    All rights reserved. This program and the accompanying materials are
 *    made available under the terms of the Apache License, Version 2.0
 *    which accompanies this distribution, and is available at
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 *    Copyright 2016 Open Connectivity Foundation and Contributors to
 *    AllSeen Alliance. All rights reserved.
 *
 *    Permission to use, copy, modify, and/or distribute this software for
 *    any purpose with or without fee is hereby granted, provided that the
 *    above copyright notice and this permission notice appear in all
 *    copies.
 *
 *     THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL
 *     WARRANTIES WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED
 *     WARRANTIES OF MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE
 *     AUTHOR BE LIABLE FOR ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL
 *     DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR
 *     PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER
 *     TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR
 *     PERFORMANCE OF THIS SOFTWARE.
 ******************************************************************************/

// This file is automatically generated. Do not edit it.

#include <alljoyn/cdm/common/LogModule.h>
#include <alljoyn/cdm/common/CdmTypes.h>
#include <alljoyn/cdm/controller/InterfaceController.h>
#include <interfaces/controller/operation/AlertsIntfControllerListener.h>
#include <interfaces/controller/operation/AlertsIntfController.h>

using namespace qcc;
using namespace std;

namespace ajn {
namespace services {
//======================================================================

typedef Ref<AlertsIntfControllerListener> MyInterfaceListener;


class AlertsIntfController::Impl : public InterfaceController
{
  public:

    Impl(
        AlertsIntfController& outer,
        BusAttachment& busAttachment,
        MyInterfaceListener listener,
        Ref<ProxyBusObject> proxyBusObject
        )
      : InterfaceController(proxyBusObject),
        m_outer(outer),
        m_busAttachment(busAttachment),
        m_interfaceListener(listener)
    {
    }

    QStatus Init();

    const char* GetInterfaceName() const
    {
        return m_outer.GetInterfaceName().c_str();
    }

    QStatus GetAlerts(void* context);

    virtual QStatus GetAlertCodesDescription(const qcc::String& languageTag, void* context);
    virtual QStatus AcknowledgeAlert(const uint16_t alertCode, void* context);
    virtual QStatus AcknowledgeAllAlerts(void* context);

    void PropertiesChanged(ProxyBusObject& obj, const char* ifaceName, const MsgArg& changed, const MsgArg& invalidated, void* context);

    void GetAlertsPropertyCB(QStatus status, ProxyBusObject* obj, const MsgArg& value, void* context);

    void GetAlertCodesDescriptionReplyHandler(Message& message, void* context);
    void AcknowledgeAlertReplyHandler(Message& message, void* context);
    void AcknowledgeAllAlertsReplyHandler(Message& message, void* context);


    // The outer facet
    AlertsIntfController& m_outer;

    // and inherit m_proxyObject from InterfaceController
    BusAttachment& m_busAttachment;
    MyInterfaceListener m_interfaceListener;
};

//======================================================================

QStatus AlertsIntfController::Impl::Init()
{
    auto status = m_proxyObject->RegisterPropertiesChangedListener(GetInterfaceName(), NULL, 0, *this, NULL);

    if (ER_OK != status) {
        QCC_LogError(status, ("%s: RegisterPropertiesChangedListener failed.", __func__));
    }

    const InterfaceDescription* intf = m_outer.GetInterfaceDescription();
    if (intf) {
    } else {
        status = ER_FAIL;
        QCC_LogError(status, ("%s: The interface description does not exist.", __func__));
    }

    return status;
}




QStatus AlertsIntfController::Impl::GetAlerts(void* context)
{
    auto status = m_proxyObject->GetPropertyAsync(GetInterfaceName(), s_prop_Alerts.c_str(), this,
                (ProxyBusObject::Listener::GetPropertyCB)&AlertsIntfController::Impl::GetAlertsPropertyCB, context);
    return status;
}



QStatus AlertsIntfController::Impl::GetAlertCodesDescription(const qcc::String& languageTag, void* context)
{
    // Method call
    static const size_t numInputs = 1;
    MsgArg args[numInputs];

    {
        CdmMsgCvt<qcc::String> converter;
        converter.set(args[0], languageTag);
    }

    auto status = m_proxyObject->MethodCallAsync(GetInterfaceName(), s_method_GetAlertCodesDescription.c_str(), this,
                (MessageReceiver::ReplyHandler)&AlertsIntfController::Impl::GetAlertCodesDescriptionReplyHandler,
                args, numInputs, context);
    return status;
}

QStatus AlertsIntfController::Impl::AcknowledgeAlert(const uint16_t alertCode, void* context)
{
    // Method call
    static const size_t numInputs = 1;
    MsgArg args[numInputs];

    {
        CdmMsgCvt<uint16_t> converter;
        converter.set(args[0], alertCode);
    }

    auto status = m_proxyObject->MethodCallAsync(GetInterfaceName(), s_method_AcknowledgeAlert.c_str(), this,
                (MessageReceiver::ReplyHandler)&AlertsIntfController::Impl::AcknowledgeAlertReplyHandler,
                args, numInputs, context);
    return status;
}

QStatus AlertsIntfController::Impl::AcknowledgeAllAlerts(void* context)
{
    // Method call
    static const size_t numInputs = 0;
    MsgArg* args = 0;

    auto status = m_proxyObject->MethodCallAsync(GetInterfaceName(), s_method_AcknowledgeAllAlerts.c_str(), this,
                (MessageReceiver::ReplyHandler)&AlertsIntfController::Impl::AcknowledgeAllAlertsReplyHandler,
                args, numInputs, context);
    return status;
}



void AlertsIntfController::Impl::PropertiesChanged(ProxyBusObject& obj, const char* ifaceName, const MsgArg& changed, const MsgArg& invalidated, void* context)
{
    MsgArg* entries;
    size_t numEntries;

    changed.Get("a{sv}", &numEntries, &entries);
    for (size_t i = 0; i < numEntries; ++i) {
        const char* propName;
        MsgArg* propValue;
        entries[i].Get("{sv}", &propName, &propValue);
        String propNameStr(propName);

        if (s_prop_Alerts == propNameStr) {
            std::vector<AlertsInterface::AlertRecord> val;
            {
                CdmMsgCvt<std::vector<AlertsInterface::AlertRecord>> converter;
                converter.get((*propValue), val);
            }
            m_interfaceListener->OnAlertsChanged(obj.GetPath(), val);
        } else {
            QCC_DbgTrace(("Unknown property change signal received"));
        }
    }
}

//======================================================================
// Callbacks


void AlertsIntfController::Impl::GetAlertsPropertyCB(QStatus status, ProxyBusObject* obj, const MsgArg& value, void* context)
{
    if (obj) {
        std::vector<AlertsInterface::AlertRecord> val;
        {
            CdmMsgCvt<std::vector<AlertsInterface::AlertRecord>> converter;
            converter.get(value, val);
        }
        if (_QCC_DbgPrintCheck(DBG_GEN_MESSAGE, QCC_MODULE)) {
            auto s = CdmMsgCvt<std::vector<AlertsInterface::AlertRecord>>().str(value);
            QCC_DbgPrintf(("%s: received property %s=%s", __func__, "Alerts", s.c_str()));
        }
        m_interfaceListener->OnResponseGetAlerts(status, obj->GetPath(), val, context);
    }
}






void AlertsIntfController::Impl::GetAlertCodesDescriptionReplyHandler(Message& message, void* context)
{
    qcc::String errorMessage;
    const char* errorName = message->GetErrorName(&errorMessage);
    QStatus status = ER_OK;
    size_t numArgs = 0;
    const MsgArg* args = 0;

    std::vector<AlertsInterface::AlertCodesDescriptor> arg_description;

    if (message->GetType() == MESSAGE_METHOD_RET) {
        message->GetArgs(numArgs, args);
        CdmMsgCvt<std::vector<AlertsInterface::AlertCodesDescriptor>> cvt_description;
        cvt_description.get(args[0], arg_description);

        if (_QCC_DbgPrintCheck(DBG_GEN_MESSAGE, QCC_MODULE)) {
            auto s = cvt_description.str(args[0]);
            QCC_DbgPrintf(("%s: received reply with %s=%s", __func__, "description", s.c_str()));
        }
    } else {
        status = ER_FAIL;
    }

    m_interfaceListener->OnResponseGetAlertCodesDescription(status, m_proxyObject->GetPath(), arg_description, context, errorName, errorMessage.c_str());
}



void AlertsIntfController::Impl::AcknowledgeAlertReplyHandler(Message& message, void* context)
{
    qcc::String errorMessage;
    const char* errorName = message->GetErrorName(&errorMessage);
    QStatus status = ER_OK;
    size_t numArgs = 0;
    const MsgArg* args = 0;


    if (message->GetType() == MESSAGE_METHOD_RET) {
        message->GetArgs(numArgs, args);
    } else {
        status = ER_FAIL;
    }

    m_interfaceListener->OnResponseAcknowledgeAlert(status, m_proxyObject->GetPath(), context, errorName, errorMessage.c_str());
}



void AlertsIntfController::Impl::AcknowledgeAllAlertsReplyHandler(Message& message, void* context)
{
    qcc::String errorMessage;
    const char* errorName = message->GetErrorName(&errorMessage);
    QStatus status = ER_OK;
    size_t numArgs = 0;
    const MsgArg* args = 0;


    if (message->GetType() == MESSAGE_METHOD_RET) {
        message->GetArgs(numArgs, args);
    } else {
        status = ER_FAIL;
    }

    m_interfaceListener->OnResponseAcknowledgeAllAlerts(status, m_proxyObject->GetPath(), context, errorName, errorMessage.c_str());
}

//======================================================================
// Forward to the impl

AlertsIntfController::AlertsIntfController(
    BusAttachment& busAttachment,
    Ref<InterfaceControllerListener> listener,
    Ref<ProxyBusObject> cdmProxyObject
    )
  : m_impl(new Impl(*this, busAttachment, dynamic_pointer_cast<AlertsIntfControllerListener>(listener), cdmProxyObject))
{
}



AlertsIntfController::~AlertsIntfController()
{
    delete m_impl;
}



Ref<CdmInterface> AlertsIntfController::CreateInterface(BusAttachment& busAttachment, Ref<InterfaceControllerListener> listener, Ref<ProxyBusObject> cdmProxyObject)
{
    return mkRef<AlertsIntfController>(busAttachment, dynamic_pointer_cast<AlertsIntfControllerListener>(listener), cdmProxyObject);
}



QStatus AlertsIntfController::Init()
{
    // Call the superclass Init
    QStatus status = CdmInterface::Init();
    if (ER_OK != status) {
        QCC_LogError(status, ("%s: Interface init failed.", __func__));
        return status;
    }

    return m_impl->Init();
}



BusAttachment& AlertsIntfController::GetBusAttachment() const
{
    return m_impl->m_busAttachment;
}



QStatus AlertsIntfController::GetAlerts(void* context)
{
    return m_impl->GetAlerts(context);
}



QStatus AlertsIntfController::GetAlertCodesDescription(const qcc::String& languageTag, void* context)
{
    return m_impl->GetAlertCodesDescription(languageTag, context);
}



QStatus AlertsIntfController::AcknowledgeAlert(const uint16_t alertCode, void* context)
{
    return m_impl->AcknowledgeAlert(alertCode, context);
}



QStatus AlertsIntfController::AcknowledgeAllAlerts(void* context)
{
    return m_impl->AcknowledgeAllAlerts(context);
}

//======================================================================
} //namespace services
} //namespace ajn
