/******************************************************************************
 *  *    Copyright (c) Open Connectivity Foundation (OCF) and AllJoyn Open
 *    Source Project (AJOSP) Contributors and others.
 *
 *    SPDX-License-Identifier: Apache-2.0
 *
 *    All rights reserved. This program and the accompanying materials are
 *    made available under the terms of the Apache License, Version 2.0
 *    which accompanies this distribution, and is available at
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 *    Copyright (c) Open Connectivity Foundation and Contributors to AllSeen
 *    Alliance. All rights reserved.
 *
 *    Permission to use, copy, modify, and/or distribute this software for
 *    any purpose with or without fee is hereby granted, provided that the
 *    above copyright notice and this permission notice appear in all
 *    copies.
 *
 *     THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL
 *     WARRANTIES WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED
 *     WARRANTIES OF MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE
 *     AUTHOR BE LIABLE FOR ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL
 *     DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR
 *     PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER
 *     TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR
 *     PERFORMANCE OF THIS SOFTWARE.
 ******************************************************************************/

// This file is automatically generated. Do not edit it.

#include <alljoyn/cdm/common/LogModule.h>
#include <alljoyn/cdm/common/CdmTypes.h>
#include <alljoyn/cdm/controller/InterfaceController.h>
#include <interfaces/controller/operation/ChannelIntfControllerListener.h>
#include <interfaces/controller/operation/ChannelIntfController.h>

using namespace qcc;
using namespace std;

namespace ajn {
namespace services {
//======================================================================

typedef Ref<ChannelIntfControllerListener> MyInterfaceListener;


class ChannelIntfController::Impl : public InterfaceController
{
  public:

    Impl(
        ChannelIntfController& outer,
        BusAttachment& busAttachment,
        MyInterfaceListener listener,
        Ref<ProxyBusObject> proxyBusObject
        )
      : InterfaceController(proxyBusObject),
        m_outer(outer),
        m_busAttachment(busAttachment),
        m_interfaceListener(listener)
    {
    }

    QStatus Init();

    const char* GetInterfaceName() const
    {
        return m_outer.GetInterfaceName().c_str();
    }

    QStatus GetChannelId(void* context);
    QStatus SetChannelId(const qcc::String& value, void* context);
    QStatus GetTotalNumberOfChannels(void* context);

    virtual QStatus GetChannelList(const uint16_t startingRecord, const uint16_t numRecords, void* context);

    void PropertiesChanged(ProxyBusObject& obj, const char* ifaceName, const MsgArg& changed, const MsgArg& invalidated, void* context);

    void GetChannelIdPropertyCB(QStatus status, ProxyBusObject* obj, const MsgArg& value, void* context);
    void SetChannelIdPropertyCB(QStatus status, ProxyBusObject* obj, void* context);
    void GetTotalNumberOfChannelsPropertyCB(QStatus status, ProxyBusObject* obj, const MsgArg& value, void* context);

    void GetChannelListReplyHandler(Message& message, void* context);

    void ChannelListChanged(const InterfaceDescription::Member* member, const char* srcPath, Message& message);

    // The outer facet
    ChannelIntfController& m_outer;

    // and inherit m_proxyObject from InterfaceController
    BusAttachment& m_busAttachment;
    MyInterfaceListener m_interfaceListener;
};

//======================================================================

QStatus ChannelIntfController::Impl::Init()
{
    auto status = m_proxyObject->RegisterPropertiesChangedListener(GetInterfaceName(), NULL, 0, *this, NULL);

    if (ER_OK != status) {
        QCC_LogError(status, ("%s: RegisterPropertiesChangedListener failed.", __func__));
    }

    const InterfaceDescription* intf = m_outer.GetInterfaceDescription();
    if (intf) {
        const InterfaceDescription::Member* member = intf->GetMember(s_signal_ChannelListChanged.c_str());
        if (member) {
            status = m_busAttachment.RegisterSignalHandler(this, static_cast<SignalHandler>(&ChannelIntfController::Impl::ChannelListChanged), member, NULL);
            if (ER_OK != status) {
                QCC_LogError(status, ("%s: RegisterSignalHandler for ChannelListChanged signal failed.", __func__));
            }
        } else {
            status = ER_FAIL;
            QCC_LogError(status, ("%s: ChannelListChanged signal does not exist.", __func__));
        }
    } else {
        status = ER_FAIL;
        QCC_LogError(status, ("%s: The interface description does not exist.", __func__));
    }

    return status;
}




QStatus ChannelIntfController::Impl::GetChannelId(void* context)
{
    auto status = m_proxyObject->GetPropertyAsync(GetInterfaceName(), s_prop_ChannelId.c_str(), this,
                (ProxyBusObject::Listener::GetPropertyCB)&ChannelIntfController::Impl::GetChannelIdPropertyCB, context);
    return status;
}

QStatus ChannelIntfController::Impl::SetChannelId(const qcc::String& value, void* context)
{
    MsgArg arg;
    {
        CdmMsgCvt<qcc::String> converter;
        converter.set(arg, value);
    }

    auto status = m_proxyObject->SetPropertyAsync(GetInterfaceName(), s_prop_ChannelId.c_str(), arg, this,
                (ProxyBusObject::Listener::SetPropertyCB)&ChannelIntfController::Impl::SetChannelIdPropertyCB, context);
    return status;
}

QStatus ChannelIntfController::Impl::GetTotalNumberOfChannels(void* context)
{
    auto status = m_proxyObject->GetPropertyAsync(GetInterfaceName(), s_prop_TotalNumberOfChannels.c_str(), this,
                (ProxyBusObject::Listener::GetPropertyCB)&ChannelIntfController::Impl::GetTotalNumberOfChannelsPropertyCB, context);
    return status;
}



QStatus ChannelIntfController::Impl::GetChannelList(const uint16_t startingRecord, const uint16_t numRecords, void* context)
{
    // Method call
    static const size_t numInputs = 2;
    MsgArg args[numInputs];

    {
        CdmMsgCvt<uint16_t> converter;
        converter.set(args[0], startingRecord);
    }
    {
        CdmMsgCvt<uint16_t> converter;
        converter.set(args[1], numRecords);
    }

    auto status = m_proxyObject->MethodCallAsync(GetInterfaceName(), s_method_GetChannelList.c_str(), this,
                (MessageReceiver::ReplyHandler)&ChannelIntfController::Impl::GetChannelListReplyHandler,
                args, numInputs, context);
    return status;
}



void ChannelIntfController::Impl::PropertiesChanged(ProxyBusObject& obj, const char* ifaceName, const MsgArg& changed, const MsgArg& invalidated, void* context)
{
    MsgArg* entries;
    size_t numEntries;

    changed.Get("a{sv}", &numEntries, &entries);
    for (size_t i = 0; i < numEntries; ++i) {
        const char* propName;
        MsgArg* propValue;
        entries[i].Get("{sv}", &propName, &propValue);
        String propNameStr(propName);

        if (s_prop_ChannelId == propNameStr) {
            qcc::String val;
            {
                CdmMsgCvt<qcc::String> converter;
                converter.get((*propValue), val);
            }
            m_interfaceListener->OnChannelIdChanged(obj.GetPath(), val);
        } else if (s_prop_TotalNumberOfChannels == propNameStr) {
            uint16_t val;
            {
                CdmMsgCvt<uint16_t> converter;
                converter.get((*propValue), val);
            }
            m_interfaceListener->OnTotalNumberOfChannelsChanged(obj.GetPath(), val);
        } else {
            QCC_DbgTrace(("Unknown property change signal received"));
        }
    }
}

//======================================================================
// Callbacks


void ChannelIntfController::Impl::GetChannelIdPropertyCB(QStatus status, ProxyBusObject* obj, const MsgArg& value, void* context)
{
    if (obj) {
        qcc::String val;
        {
            CdmMsgCvt<qcc::String> converter;
            converter.get(value, val);
        }
        if (_QCC_DbgPrintCheck(DBG_GEN_MESSAGE, QCC_MODULE)) {
            auto s = CdmMsgCvt<qcc::String>().str(value);
            QCC_DbgPrintf(("%s: received property %s=%s", __func__, "ChannelId", s.c_str()));
        }
        m_interfaceListener->OnResponseGetChannelId(status, obj->GetPath(), val, context);
    }
}



void ChannelIntfController::Impl::SetChannelIdPropertyCB(QStatus status, ProxyBusObject* obj, void* context)
{
    QCC_DbgPrintf(("%s: set completed", __func__));
    if (obj) {
        m_interfaceListener->OnResponseSetChannelId(status, obj->GetPath(), context);
    }
}

void ChannelIntfController::Impl::GetTotalNumberOfChannelsPropertyCB(QStatus status, ProxyBusObject* obj, const MsgArg& value, void* context)
{
    if (obj) {
        uint16_t val;
        {
            CdmMsgCvt<uint16_t> converter;
            converter.get(value, val);
        }
        if (_QCC_DbgPrintCheck(DBG_GEN_MESSAGE, QCC_MODULE)) {
            auto s = CdmMsgCvt<uint16_t>().str(value);
            QCC_DbgPrintf(("%s: received property %s=%s", __func__, "TotalNumberOfChannels", s.c_str()));
        }
        m_interfaceListener->OnResponseGetTotalNumberOfChannels(status, obj->GetPath(), val, context);
    }
}






void ChannelIntfController::Impl::GetChannelListReplyHandler(Message& message, void* context)
{
    qcc::String errorMessage;
    const char* errorName = message->GetErrorName(&errorMessage);
    QStatus status = ER_OK;
    size_t numArgs = 0;
    const MsgArg* args = 0;

    std::vector<ChannelInterface::ChannelInfoRecord> arg_listOfChannelInfoRecords;

    if (message->GetType() == MESSAGE_METHOD_RET) {
        message->GetArgs(numArgs, args);
        CdmMsgCvt<std::vector<ChannelInterface::ChannelInfoRecord>> cvt_listOfChannelInfoRecords;
        cvt_listOfChannelInfoRecords.get(args[0], arg_listOfChannelInfoRecords);

        if (_QCC_DbgPrintCheck(DBG_GEN_MESSAGE, QCC_MODULE)) {
            auto s = cvt_listOfChannelInfoRecords.str(args[0]);
            QCC_DbgPrintf(("%s: received reply with %s=%s", __func__, "listOfChannelInfoRecords", s.c_str()));
        }
    } else {
        status = ER_FAIL;
    }

    m_interfaceListener->OnResponseGetChannelList(status, m_proxyObject->GetPath(), arg_listOfChannelInfoRecords, context, errorName, errorMessage.c_str());
}



void ChannelIntfController::Impl::ChannelListChanged(const InterfaceDescription::Member* member, const char* srcPath, Message& message)
{
    String path = String(srcPath);

    QCC_DbgPrintf(("%s: received signal %s", __func__, "ChannelListChanged"));
    m_interfaceListener->OnChannelListChanged(path);
}

//======================================================================
// Forward to the impl

ChannelIntfController::ChannelIntfController(
    BusAttachment& busAttachment,
    Ref<InterfaceControllerListener> listener,
    Ref<ProxyBusObject> cdmProxyObject
    )
  : m_impl(new Impl(*this, busAttachment, dynamic_pointer_cast<ChannelIntfControllerListener>(listener), cdmProxyObject))
{
}



ChannelIntfController::~ChannelIntfController()
{
    delete m_impl;
}



Ref<CdmInterface> ChannelIntfController::CreateInterface(BusAttachment& busAttachment, Ref<InterfaceControllerListener> listener, Ref<ProxyBusObject> cdmProxyObject)
{
    return mkRef<ChannelIntfController>(busAttachment, dynamic_pointer_cast<ChannelIntfControllerListener>(listener), cdmProxyObject);
}



QStatus ChannelIntfController::Init()
{
    // Call the superclass Init
    QStatus status = CdmInterface::Init();
    if (ER_OK != status) {
        QCC_LogError(status, ("%s: Interface init failed.", __func__));
        return status;
    }

    return m_impl->Init();
}



BusAttachment& ChannelIntfController::GetBusAttachment() const
{
    return m_impl->m_busAttachment;
}



QStatus ChannelIntfController::GetChannelId(void* context)
{
    return m_impl->GetChannelId(context);
}



QStatus ChannelIntfController::SetChannelId(const qcc::String& value, void* context)
{
    return m_impl->SetChannelId(value, context);
}



QStatus ChannelIntfController::GetTotalNumberOfChannels(void* context)
{
    return m_impl->GetTotalNumberOfChannels(context);
}



QStatus ChannelIntfController::GetChannelList(const uint16_t startingRecord, const uint16_t numRecords, void* context)
{
    return m_impl->GetChannelList(startingRecord, numRecords, context);
}

//======================================================================
} //namespace services
} //namespace ajn