/******************************************************************************
 *  * Copyright (c) Open Connectivity Foundation (OCF) and AllJoyn Open
 *    Source Project (AJOSP) Contributors and others.
 *
 *    SPDX-License-Identifier: Apache-2.0
 *
 *    All rights reserved. This program and the accompanying materials are
 *    made available under the terms of the Apache License, Version 2.0
 *    which accompanies this distribution, and is available at
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 *    Copyright (c) Open Connectivity Foundation and Contributors to AllSeen
 *    Alliance. All rights reserved.
 *
 *    Permission to use, copy, modify, and/or distribute this software for
 *    any purpose with or without fee is hereby granted, provided that the
 *    above copyright notice and this permission notice appear in all
 *    copies.
 *
 *     THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL
 *     WARRANTIES WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED
 *     WARRANTIES OF MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE
 *     AUTHOR BE LIABLE FOR ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL
 *     DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR
 *     PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER
 *     TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR
 *     PERFORMANCE OF THIS SOFTWARE.
 ******************************************************************************/

// This file is automatically generated. Do not edit it.

#include <alljoyn/cdm/common/LogModule.h>
#include <alljoyn/cdm/common/CdmTypes.h>
#include <alljoyn/cdm/controller/InterfaceController.h>
#include <interfaces/controller/operation/ColorTemperatureIntfControllerListener.h>
#include <interfaces/controller/operation/ColorTemperatureIntfController.h>

using namespace qcc;
using namespace std;

namespace ajn {
namespace services {
//======================================================================

typedef Ref<ColorTemperatureIntfControllerListener> MyInterfaceListener;


class ColorTemperatureIntfController::Impl : public InterfaceController
{
  public:

    Impl(
        ColorTemperatureIntfController& outer,
        BusAttachment& busAttachment,
        MyInterfaceListener listener,
        Ref<ProxyBusObject> proxyBusObject
        )
      : InterfaceController(proxyBusObject),
        m_outer(outer),
        m_busAttachment(busAttachment),
        m_interfaceListener(listener)
    {
    }

    QStatus Init();

    const char* GetInterfaceName() const
    {
        return m_outer.GetInterfaceName().c_str();
    }

    QStatus GetTemperature(void* context);
    QStatus SetTemperature(const double value, void* context);
    QStatus GetMinTemperature(void* context);
    QStatus GetMaxTemperature(void* context);


    void PropertiesChanged(ProxyBusObject& obj, const char* ifaceName, const MsgArg& changed, const MsgArg& invalidated, void* context);

    void GetTemperaturePropertyCB(QStatus status, ProxyBusObject* obj, const MsgArg& value, void* context);
    void SetTemperaturePropertyCB(QStatus status, ProxyBusObject* obj, void* context);
    void GetMinTemperaturePropertyCB(QStatus status, ProxyBusObject* obj, const MsgArg& value, void* context);
    void GetMaxTemperaturePropertyCB(QStatus status, ProxyBusObject* obj, const MsgArg& value, void* context);



    // The outer facet
    ColorTemperatureIntfController& m_outer;

    // and inherit m_proxyObject from InterfaceController
    BusAttachment& m_busAttachment;
    MyInterfaceListener m_interfaceListener;
};

//======================================================================

QStatus ColorTemperatureIntfController::Impl::Init()
{
    auto status = m_proxyObject->RegisterPropertiesChangedListener(GetInterfaceName(), NULL, 0, *this, NULL);

    if (ER_OK != status) {
        QCC_LogError(status, ("%s: RegisterPropertiesChangedListener failed.", __func__));
    }

    const InterfaceDescription* intf = m_outer.GetInterfaceDescription();
    if (intf) {
    } else {
        status = ER_FAIL;
        QCC_LogError(status, ("%s: The interface description does not exist.", __func__));
    }

    return status;
}




QStatus ColorTemperatureIntfController::Impl::GetTemperature(void* context)
{
    auto status = m_proxyObject->GetPropertyAsync(GetInterfaceName(), s_prop_Temperature.c_str(), this,
                (ProxyBusObject::Listener::GetPropertyCB)&ColorTemperatureIntfController::Impl::GetTemperaturePropertyCB, context);
    return status;
}

QStatus ColorTemperatureIntfController::Impl::SetTemperature(const double value, void* context)
{
    MsgArg arg;
    {
        CdmMsgCvt<double> converter;
        converter.set(arg, value);
    }

    auto status = m_proxyObject->SetPropertyAsync(GetInterfaceName(), s_prop_Temperature.c_str(), arg, this,
                (ProxyBusObject::Listener::SetPropertyCB)&ColorTemperatureIntfController::Impl::SetTemperaturePropertyCB, context);
    return status;
}

QStatus ColorTemperatureIntfController::Impl::GetMinTemperature(void* context)
{
    auto status = m_proxyObject->GetPropertyAsync(GetInterfaceName(), s_prop_MinTemperature.c_str(), this,
                (ProxyBusObject::Listener::GetPropertyCB)&ColorTemperatureIntfController::Impl::GetMinTemperaturePropertyCB, context);
    return status;
}

QStatus ColorTemperatureIntfController::Impl::GetMaxTemperature(void* context)
{
    auto status = m_proxyObject->GetPropertyAsync(GetInterfaceName(), s_prop_MaxTemperature.c_str(), this,
                (ProxyBusObject::Listener::GetPropertyCB)&ColorTemperatureIntfController::Impl::GetMaxTemperaturePropertyCB, context);
    return status;
}





void ColorTemperatureIntfController::Impl::PropertiesChanged(ProxyBusObject& obj, const char* ifaceName, const MsgArg& changed, const MsgArg& invalidated, void* context)
{
    MsgArg* entries;
    size_t numEntries;

    changed.Get("a{sv}", &numEntries, &entries);
    for (size_t i = 0; i < numEntries; ++i) {
        const char* propName;
        MsgArg* propValue;
        entries[i].Get("{sv}", &propName, &propValue);
        String propNameStr(propName);

        if (s_prop_Temperature == propNameStr) {
            double val;
            {
                CdmMsgCvt<double> converter;
                converter.get((*propValue), val);
            }
            m_interfaceListener->OnTemperatureChanged(obj.GetPath(), val);
        } else if (s_prop_MinTemperature == propNameStr) {
            double val;
            {
                CdmMsgCvt<double> converter;
                converter.get((*propValue), val);
            }
            m_interfaceListener->OnMinTemperatureChanged(obj.GetPath(), val);
        } else if (s_prop_MaxTemperature == propNameStr) {
            double val;
            {
                CdmMsgCvt<double> converter;
                converter.get((*propValue), val);
            }
            m_interfaceListener->OnMaxTemperatureChanged(obj.GetPath(), val);
        } else {
            QCC_DbgTrace(("Unknown property change signal received"));
        }
    }
}

//======================================================================
// Callbacks


void ColorTemperatureIntfController::Impl::GetTemperaturePropertyCB(QStatus status, ProxyBusObject* obj, const MsgArg& value, void* context)
{
    if (obj) {
        double val;
        {
            CdmMsgCvt<double> converter;
            converter.get(value, val);
        }
        if (_QCC_DbgPrintCheck(DBG_GEN_MESSAGE, QCC_MODULE)) {
            auto s = CdmMsgCvt<double>().str(value);
            QCC_DbgPrintf(("%s: received property %s=%s", __func__, "Temperature", s.c_str()));
        }
        m_interfaceListener->OnResponseGetTemperature(status, obj->GetPath(), val, context);
    }
}



void ColorTemperatureIntfController::Impl::SetTemperaturePropertyCB(QStatus status, ProxyBusObject* obj, void* context)
{
    QCC_DbgPrintf(("%s: set completed", __func__));
    if (obj) {
        m_interfaceListener->OnResponseSetTemperature(status, obj->GetPath(), context);
    }
}

void ColorTemperatureIntfController::Impl::GetMinTemperaturePropertyCB(QStatus status, ProxyBusObject* obj, const MsgArg& value, void* context)
{
    if (obj) {
        double val;
        {
            CdmMsgCvt<double> converter;
            converter.get(value, val);
        }
        if (_QCC_DbgPrintCheck(DBG_GEN_MESSAGE, QCC_MODULE)) {
            auto s = CdmMsgCvt<double>().str(value);
            QCC_DbgPrintf(("%s: received property %s=%s", __func__, "MinTemperature", s.c_str()));
        }
        m_interfaceListener->OnResponseGetMinTemperature(status, obj->GetPath(), val, context);
    }
}




void ColorTemperatureIntfController::Impl::GetMaxTemperaturePropertyCB(QStatus status, ProxyBusObject* obj, const MsgArg& value, void* context)
{
    if (obj) {
        double val;
        {
            CdmMsgCvt<double> converter;
            converter.get(value, val);
        }
        if (_QCC_DbgPrintCheck(DBG_GEN_MESSAGE, QCC_MODULE)) {
            auto s = CdmMsgCvt<double>().str(value);
            QCC_DbgPrintf(("%s: received property %s=%s", __func__, "MaxTemperature", s.c_str()));
        }
        m_interfaceListener->OnResponseGetMaxTemperature(status, obj->GetPath(), val, context);
    }
}




//======================================================================
// Forward to the impl

ColorTemperatureIntfController::ColorTemperatureIntfController(
    BusAttachment& busAttachment,
    Ref<InterfaceControllerListener> listener,
    Ref<ProxyBusObject> cdmProxyObject
    )
  : m_impl(new Impl(*this, busAttachment, dynamic_pointer_cast<ColorTemperatureIntfControllerListener>(listener), cdmProxyObject))
{
}



ColorTemperatureIntfController::~ColorTemperatureIntfController()
{
    delete m_impl;
}



Ref<CdmInterface> ColorTemperatureIntfController::CreateInterface(BusAttachment& busAttachment, Ref<InterfaceControllerListener> listener, Ref<ProxyBusObject> cdmProxyObject)
{
    return mkRef<ColorTemperatureIntfController>(busAttachment, dynamic_pointer_cast<ColorTemperatureIntfControllerListener>(listener), cdmProxyObject);
}



QStatus ColorTemperatureIntfController::Init()
{
    // Call the superclass Init
    QStatus status = CdmInterface::Init();
    if (ER_OK != status) {
        QCC_LogError(status, ("%s: Interface init failed.", __func__));
        return status;
    }

    return m_impl->Init();
}



BusAttachment& ColorTemperatureIntfController::GetBusAttachment() const
{
    return m_impl->m_busAttachment;
}



QStatus ColorTemperatureIntfController::GetTemperature(void* context)
{
    return m_impl->GetTemperature(context);
}



QStatus ColorTemperatureIntfController::SetTemperature(const double value, void* context)
{
    return m_impl->SetTemperature(value, context);
}



QStatus ColorTemperatureIntfController::GetMinTemperature(void* context)
{
    return m_impl->GetMinTemperature(context);
}



QStatus ColorTemperatureIntfController::GetMaxTemperature(void* context)
{
    return m_impl->GetMaxTemperature(context);
}

//======================================================================
} //namespace services
} //namespace ajn