/******************************************************************************
 * Copyright (c) 2016 Open Connectivity Foundation (OCF) and AllJoyn Open
 *    Source Project (AJOSP) Contributors and others.
 *
 *    SPDX-License-Identifier: Apache-2.0
 *
 *    All rights reserved. This program and the accompanying materials are
 *    made available under the terms of the Apache License, Version 2.0
 *    which accompanies this distribution, and is available at
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 *    Copyright 2016 Open Connectivity Foundation and Contributors to
 *    AllSeen Alliance. All rights reserved.
 *
 *    Permission to use, copy, modify, and/or distribute this software for
 *    any purpose with or without fee is hereby granted, provided that the
 *    above copyright notice and this permission notice appear in all
 *    copies.
 *
 *     THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL
 *     WARRANTIES WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED
 *     WARRANTIES OF MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE
 *     AUTHOR BE LIABLE FOR ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL
 *     DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR
 *     PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER
 *     TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR
 *     PERFORMANCE OF THIS SOFTWARE.
 ******************************************************************************/

// This file is automatically generated. Do not edit it.

#include <alljoyn/cdm/common/LogModule.h>
#include <alljoyn/cdm/common/CdmTypes.h>
#include <alljoyn/cdm/controller/InterfaceController.h>
#include <interfaces/controller/operation/FanSpeedLevelIntfControllerListener.h>
#include <interfaces/controller/operation/FanSpeedLevelIntfController.h>

using namespace qcc;
using namespace std;

namespace ajn {
namespace services {
//======================================================================

typedef Ref<FanSpeedLevelIntfControllerListener> MyInterfaceListener;


class FanSpeedLevelIntfController::Impl : public InterfaceController
{
  public:

    Impl(
        FanSpeedLevelIntfController& outer,
        BusAttachment& busAttachment,
        MyInterfaceListener listener,
        Ref<ProxyBusObject> proxyBusObject
        )
      : InterfaceController(proxyBusObject),
        m_outer(outer),
        m_busAttachment(busAttachment),
        m_interfaceListener(listener)
    {
    }

    QStatus Init();

    const char* GetInterfaceName() const
    {
        return m_outer.GetInterfaceName().c_str();
    }

    QStatus GetFanSpeedLevel(void* context);
    QStatus SetFanSpeedLevel(const uint8_t value, void* context);
    QStatus GetMaxFanSpeedLevel(void* context);
    QStatus GetAutoMode(void* context);
    QStatus SetAutoMode(const FanSpeedLevelInterface::AutoMode value, void* context);


    void PropertiesChanged(ProxyBusObject& obj, const char* ifaceName, const MsgArg& changed, const MsgArg& invalidated, void* context);

    void GetFanSpeedLevelPropertyCB(QStatus status, ProxyBusObject* obj, const MsgArg& value, void* context);
    void SetFanSpeedLevelPropertyCB(QStatus status, ProxyBusObject* obj, void* context);
    void GetMaxFanSpeedLevelPropertyCB(QStatus status, ProxyBusObject* obj, const MsgArg& value, void* context);
    void GetAutoModePropertyCB(QStatus status, ProxyBusObject* obj, const MsgArg& value, void* context);
    void SetAutoModePropertyCB(QStatus status, ProxyBusObject* obj, void* context);



    // The outer facet
    FanSpeedLevelIntfController& m_outer;

    // and inherit m_proxyObject from InterfaceController
    BusAttachment& m_busAttachment;
    MyInterfaceListener m_interfaceListener;
};

//======================================================================

QStatus FanSpeedLevelIntfController::Impl::Init()
{
    auto status = m_proxyObject->RegisterPropertiesChangedListener(GetInterfaceName(), NULL, 0, *this, NULL);

    if (ER_OK != status) {
        QCC_LogError(status, ("%s: RegisterPropertiesChangedListener failed.", __func__));
    }

    const InterfaceDescription* intf = m_outer.GetInterfaceDescription();
    if (intf) {
    } else {
        status = ER_FAIL;
        QCC_LogError(status, ("%s: The interface description does not exist.", __func__));
    }

    return status;
}




QStatus FanSpeedLevelIntfController::Impl::GetFanSpeedLevel(void* context)
{
    auto status = m_proxyObject->GetPropertyAsync(GetInterfaceName(), s_prop_FanSpeedLevel.c_str(), this,
                (ProxyBusObject::Listener::GetPropertyCB)&FanSpeedLevelIntfController::Impl::GetFanSpeedLevelPropertyCB, context);
    return status;
}

QStatus FanSpeedLevelIntfController::Impl::SetFanSpeedLevel(const uint8_t value, void* context)
{
    MsgArg arg;
    {
        CdmMsgCvt<uint8_t> converter;
        converter.set(arg, value);
    }

    auto status = m_proxyObject->SetPropertyAsync(GetInterfaceName(), s_prop_FanSpeedLevel.c_str(), arg, this,
                (ProxyBusObject::Listener::SetPropertyCB)&FanSpeedLevelIntfController::Impl::SetFanSpeedLevelPropertyCB, context);
    return status;
}

QStatus FanSpeedLevelIntfController::Impl::GetMaxFanSpeedLevel(void* context)
{
    auto status = m_proxyObject->GetPropertyAsync(GetInterfaceName(), s_prop_MaxFanSpeedLevel.c_str(), this,
                (ProxyBusObject::Listener::GetPropertyCB)&FanSpeedLevelIntfController::Impl::GetMaxFanSpeedLevelPropertyCB, context);
    return status;
}

QStatus FanSpeedLevelIntfController::Impl::GetAutoMode(void* context)
{
    auto status = m_proxyObject->GetPropertyAsync(GetInterfaceName(), s_prop_AutoMode.c_str(), this,
                (ProxyBusObject::Listener::GetPropertyCB)&FanSpeedLevelIntfController::Impl::GetAutoModePropertyCB, context);
    return status;
}

QStatus FanSpeedLevelIntfController::Impl::SetAutoMode(const FanSpeedLevelInterface::AutoMode value, void* context)
{
    MsgArg arg;
    {
        CdmMsgCvt<FanSpeedLevelInterface::AutoMode> converter;
        converter.set(arg, value);
    }

    auto status = m_proxyObject->SetPropertyAsync(GetInterfaceName(), s_prop_AutoMode.c_str(), arg, this,
                (ProxyBusObject::Listener::SetPropertyCB)&FanSpeedLevelIntfController::Impl::SetAutoModePropertyCB, context);
    return status;
}





void FanSpeedLevelIntfController::Impl::PropertiesChanged(ProxyBusObject& obj, const char* ifaceName, const MsgArg& changed, const MsgArg& invalidated, void* context)
{
    MsgArg* entries;
    size_t numEntries;

    changed.Get("a{sv}", &numEntries, &entries);
    for (size_t i = 0; i < numEntries; ++i) {
        const char* propName;
        MsgArg* propValue;
        entries[i].Get("{sv}", &propName, &propValue);
        String propNameStr(propName);

        if (s_prop_FanSpeedLevel == propNameStr) {
            uint8_t val;
            {
                CdmMsgCvt<uint8_t> converter;
                converter.get((*propValue), val);
            }
            m_interfaceListener->OnFanSpeedLevelChanged(obj.GetPath(), val);
        } else if (s_prop_MaxFanSpeedLevel == propNameStr) {
            uint8_t val;
            {
                CdmMsgCvt<uint8_t> converter;
                converter.get((*propValue), val);
            }
            m_interfaceListener->OnMaxFanSpeedLevelChanged(obj.GetPath(), val);
        } else if (s_prop_AutoMode == propNameStr) {
            FanSpeedLevelInterface::AutoMode val;
            {
                CdmMsgCvt<FanSpeedLevelInterface::AutoMode> converter;
                converter.get((*propValue), val);
            }
            m_interfaceListener->OnAutoModeChanged(obj.GetPath(), val);
        } else {
            QCC_DbgTrace(("Unknown property change signal received"));
        }
    }
}

//======================================================================
// Callbacks


void FanSpeedLevelIntfController::Impl::GetFanSpeedLevelPropertyCB(QStatus status, ProxyBusObject* obj, const MsgArg& value, void* context)
{
    if (obj) {
        uint8_t val;
        {
            CdmMsgCvt<uint8_t> converter;
            converter.get(value, val);
        }
        if (_QCC_DbgPrintCheck(DBG_GEN_MESSAGE, QCC_MODULE)) {
            auto s = CdmMsgCvt<uint8_t>().str(value);
            QCC_DbgPrintf(("%s: received property %s=%s", __func__, "FanSpeedLevel", s.c_str()));
        }
        m_interfaceListener->OnResponseGetFanSpeedLevel(status, obj->GetPath(), val, context);
    }
}



void FanSpeedLevelIntfController::Impl::SetFanSpeedLevelPropertyCB(QStatus status, ProxyBusObject* obj, void* context)
{
    QCC_DbgPrintf(("%s: set completed", __func__));
    if (obj) {
        m_interfaceListener->OnResponseSetFanSpeedLevel(status, obj->GetPath(), context);
    }
}

void FanSpeedLevelIntfController::Impl::GetMaxFanSpeedLevelPropertyCB(QStatus status, ProxyBusObject* obj, const MsgArg& value, void* context)
{
    if (obj) {
        uint8_t val;
        {
            CdmMsgCvt<uint8_t> converter;
            converter.get(value, val);
        }
        if (_QCC_DbgPrintCheck(DBG_GEN_MESSAGE, QCC_MODULE)) {
            auto s = CdmMsgCvt<uint8_t>().str(value);
            QCC_DbgPrintf(("%s: received property %s=%s", __func__, "MaxFanSpeedLevel", s.c_str()));
        }
        m_interfaceListener->OnResponseGetMaxFanSpeedLevel(status, obj->GetPath(), val, context);
    }
}




void FanSpeedLevelIntfController::Impl::GetAutoModePropertyCB(QStatus status, ProxyBusObject* obj, const MsgArg& value, void* context)
{
    if (obj) {
        FanSpeedLevelInterface::AutoMode val;
        {
            CdmMsgCvt<FanSpeedLevelInterface::AutoMode> converter;
            converter.get(value, val);
        }
        if (_QCC_DbgPrintCheck(DBG_GEN_MESSAGE, QCC_MODULE)) {
            auto s = CdmMsgCvt<FanSpeedLevelInterface::AutoMode>().str(value);
            QCC_DbgPrintf(("%s: received property %s=%s", __func__, "AutoMode", s.c_str()));
        }
        m_interfaceListener->OnResponseGetAutoMode(status, obj->GetPath(), val, context);
    }
}



void FanSpeedLevelIntfController::Impl::SetAutoModePropertyCB(QStatus status, ProxyBusObject* obj, void* context)
{
    QCC_DbgPrintf(("%s: set completed", __func__));
    if (obj) {
        m_interfaceListener->OnResponseSetAutoMode(status, obj->GetPath(), context);
    }
}

//======================================================================
// Forward to the impl

FanSpeedLevelIntfController::FanSpeedLevelIntfController(
    BusAttachment& busAttachment,
    Ref<InterfaceControllerListener> listener,
    Ref<ProxyBusObject> cdmProxyObject
    )
  : m_impl(new Impl(*this, busAttachment, dynamic_pointer_cast<FanSpeedLevelIntfControllerListener>(listener), cdmProxyObject))
{
}



FanSpeedLevelIntfController::~FanSpeedLevelIntfController()
{
    delete m_impl;
}



Ref<CdmInterface> FanSpeedLevelIntfController::CreateInterface(BusAttachment& busAttachment, Ref<InterfaceControllerListener> listener, Ref<ProxyBusObject> cdmProxyObject)
{
    return mkRef<FanSpeedLevelIntfController>(busAttachment, dynamic_pointer_cast<FanSpeedLevelIntfControllerListener>(listener), cdmProxyObject);
}



QStatus FanSpeedLevelIntfController::Init()
{
    // Call the superclass Init
    QStatus status = CdmInterface::Init();
    if (ER_OK != status) {
        QCC_LogError(status, ("%s: Interface init failed.", __func__));
        return status;
    }

    return m_impl->Init();
}



BusAttachment& FanSpeedLevelIntfController::GetBusAttachment() const
{
    return m_impl->m_busAttachment;
}



QStatus FanSpeedLevelIntfController::GetFanSpeedLevel(void* context)
{
    return m_impl->GetFanSpeedLevel(context);
}



QStatus FanSpeedLevelIntfController::SetFanSpeedLevel(const uint8_t value, void* context)
{
    return m_impl->SetFanSpeedLevel(value, context);
}



QStatus FanSpeedLevelIntfController::GetMaxFanSpeedLevel(void* context)
{
    return m_impl->GetMaxFanSpeedLevel(context);
}



QStatus FanSpeedLevelIntfController::GetAutoMode(void* context)
{
    return m_impl->GetAutoMode(context);
}



QStatus FanSpeedLevelIntfController::SetAutoMode(const FanSpeedLevelInterface::AutoMode value, void* context)
{
    return m_impl->SetAutoMode(value, context);
}

//======================================================================
} //namespace services
} //namespace ajn