/******************************************************************************
 * Copyright (c) 2016 Open Connectivity Foundation (OCF) and AllJoyn Open
 *    Source Project (AJOSP) Contributors and others.
 *
 *    SPDX-License-Identifier: Apache-2.0
 *
 *    All rights reserved. This program and the accompanying materials are
 *    made available under the terms of the Apache License, Version 2.0
 *    which accompanies this distribution, and is available at
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 *    Copyright 2016 Open Connectivity Foundation and Contributors to
 *    AllSeen Alliance. All rights reserved.
 *
 *    Permission to use, copy, modify, and/or distribute this software for
 *    any purpose with or without fee is hereby granted, provided that the
 *    above copyright notice and this permission notice appear in all
 *    copies.
 *
 *     THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL
 *     WARRANTIES WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED
 *     WARRANTIES OF MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE
 *     AUTHOR BE LIABLE FOR ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL
 *     DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR
 *     PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER
 *     TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR
 *     PERFORMANCE OF THIS SOFTWARE.
 ******************************************************************************/

// This file is automatically generated. Do not edit it.

#include <alljoyn/cdm/common/LogModule.h>
#include <alljoyn/cdm/common/CdmTypes.h>
#include <alljoyn/cdm/controller/InterfaceController.h>
#include <interfaces/controller/operation/FilterStatusIntfControllerListener.h>
#include <interfaces/controller/operation/FilterStatusIntfController.h>

using namespace qcc;
using namespace std;

namespace ajn {
namespace services {
//======================================================================

typedef Ref<FilterStatusIntfControllerListener> MyInterfaceListener;


class FilterStatusIntfController::Impl : public InterfaceController
{
  public:

    Impl(
        FilterStatusIntfController& outer,
        BusAttachment& busAttachment,
        MyInterfaceListener listener,
        Ref<ProxyBusObject> proxyBusObject
        )
      : InterfaceController(proxyBusObject),
        m_outer(outer),
        m_busAttachment(busAttachment),
        m_interfaceListener(listener)
    {
    }

    QStatus Init();

    const char* GetInterfaceName() const
    {
        return INTERFACE_NAME;
    }

    QStatus GetExpectedLifeInDays(void* context);
    QStatus GetIsCleanable(void* context);
    QStatus GetOrderPercentage(void* context);
    QStatus GetManufacturer(void* context);
    QStatus GetPartNumber(void* context);
    QStatus GetUrl(void* context);
    QStatus GetLifeRemaining(void* context);


    void PropertiesChanged(ProxyBusObject& obj, const char* ifaceName, const MsgArg& changed, const MsgArg& invalidated, void* context);

    void GetExpectedLifeInDaysPropertyCB(QStatus status, ProxyBusObject* obj, const MsgArg& value, void* context);
    void GetIsCleanablePropertyCB(QStatus status, ProxyBusObject* obj, const MsgArg& value, void* context);
    void GetOrderPercentagePropertyCB(QStatus status, ProxyBusObject* obj, const MsgArg& value, void* context);
    void GetManufacturerPropertyCB(QStatus status, ProxyBusObject* obj, const MsgArg& value, void* context);
    void GetPartNumberPropertyCB(QStatus status, ProxyBusObject* obj, const MsgArg& value, void* context);
    void GetUrlPropertyCB(QStatus status, ProxyBusObject* obj, const MsgArg& value, void* context);
    void GetLifeRemainingPropertyCB(QStatus status, ProxyBusObject* obj, const MsgArg& value, void* context);



    // The outer facet
    FilterStatusIntfController& m_outer;

    // and inherit m_proxyObject from InterfaceController
    BusAttachment& m_busAttachment;
    MyInterfaceListener m_interfaceListener;
};

//======================================================================

QStatus FilterStatusIntfController::Impl::Init()
{
    auto status = m_proxyObject->RegisterPropertiesChangedListener(GetInterfaceName(), NULL, 0, *this, NULL);

    if (ER_OK != status) {
        QCC_LogError(status, ("%s: RegisterPropertiesChangedListener failed.", __func__));
    }

    const InterfaceDescription* intf = m_outer.GetInterfaceDescription();
    if (intf) {
    } else {
        status = ER_FAIL;
        QCC_LogError(status, ("%s: The interface description does not exist.", __func__));
    }

    return status;
}




QStatus FilterStatusIntfController::Impl::GetExpectedLifeInDays(void* context)
{
    auto status = m_proxyObject->GetPropertyAsync(GetInterfaceName(), s_prop_ExpectedLifeInDays.c_str(), this,
                (ProxyBusObject::Listener::GetPropertyCB)&FilterStatusIntfController::Impl::GetExpectedLifeInDaysPropertyCB, context);
    return status;
}

QStatus FilterStatusIntfController::Impl::GetIsCleanable(void* context)
{
    auto status = m_proxyObject->GetPropertyAsync(GetInterfaceName(), s_prop_IsCleanable.c_str(), this,
                (ProxyBusObject::Listener::GetPropertyCB)&FilterStatusIntfController::Impl::GetIsCleanablePropertyCB, context);
    return status;
}

QStatus FilterStatusIntfController::Impl::GetOrderPercentage(void* context)
{
    auto status = m_proxyObject->GetPropertyAsync(GetInterfaceName(), s_prop_OrderPercentage.c_str(), this,
                (ProxyBusObject::Listener::GetPropertyCB)&FilterStatusIntfController::Impl::GetOrderPercentagePropertyCB, context);
    return status;
}

QStatus FilterStatusIntfController::Impl::GetManufacturer(void* context)
{
    auto status = m_proxyObject->GetPropertyAsync(GetInterfaceName(), s_prop_Manufacturer.c_str(), this,
                (ProxyBusObject::Listener::GetPropertyCB)&FilterStatusIntfController::Impl::GetManufacturerPropertyCB, context);
    return status;
}

QStatus FilterStatusIntfController::Impl::GetPartNumber(void* context)
{
    auto status = m_proxyObject->GetPropertyAsync(GetInterfaceName(), s_prop_PartNumber.c_str(), this,
                (ProxyBusObject::Listener::GetPropertyCB)&FilterStatusIntfController::Impl::GetPartNumberPropertyCB, context);
    return status;
}

QStatus FilterStatusIntfController::Impl::GetUrl(void* context)
{
    auto status = m_proxyObject->GetPropertyAsync(GetInterfaceName(), s_prop_Url.c_str(), this,
                (ProxyBusObject::Listener::GetPropertyCB)&FilterStatusIntfController::Impl::GetUrlPropertyCB, context);
    return status;
}

QStatus FilterStatusIntfController::Impl::GetLifeRemaining(void* context)
{
    auto status = m_proxyObject->GetPropertyAsync(GetInterfaceName(), s_prop_LifeRemaining.c_str(), this,
                (ProxyBusObject::Listener::GetPropertyCB)&FilterStatusIntfController::Impl::GetLifeRemainingPropertyCB, context);
    return status;
}





void FilterStatusIntfController::Impl::PropertiesChanged(ProxyBusObject& obj, const char* ifaceName, const MsgArg& changed, const MsgArg& invalidated, void* context)
{
    MsgArg* entries;
    size_t numEntries;

    changed.Get("a{sv}", &numEntries, &entries);
    for (size_t i = 0; i < numEntries; ++i) {
        const char* propName;
        MsgArg* propValue;
        entries[i].Get("{sv}", &propName, &propValue);
        String propNameStr(propName);

        if (s_prop_ExpectedLifeInDays == propNameStr) {
            uint16_t val;
            {
                CdmMsgCvt<uint16_t> converter;
                converter.get((*propValue), val);
            }
            m_interfaceListener->OnExpectedLifeInDaysChanged(obj.GetPath(), val);
        } else if (s_prop_IsCleanable == propNameStr) {
            bool val;
            {
                CdmMsgCvt<bool> converter;
                converter.get((*propValue), val);
            }
            m_interfaceListener->OnIsCleanableChanged(obj.GetPath(), val);
        } else if (s_prop_OrderPercentage == propNameStr) {
            uint8_t val;
            {
                CdmMsgCvt<uint8_t> converter;
                converter.get((*propValue), val);
            }
            m_interfaceListener->OnOrderPercentageChanged(obj.GetPath(), val);
        } else if (s_prop_Manufacturer == propNameStr) {
            qcc::String val;
            {
                CdmMsgCvt<qcc::String> converter;
                converter.get((*propValue), val);
            }
            m_interfaceListener->OnManufacturerChanged(obj.GetPath(), val);
        } else if (s_prop_PartNumber == propNameStr) {
            qcc::String val;
            {
                CdmMsgCvt<qcc::String> converter;
                converter.get((*propValue), val);
            }
            m_interfaceListener->OnPartNumberChanged(obj.GetPath(), val);
        } else if (s_prop_Url == propNameStr) {
            qcc::String val;
            {
                CdmMsgCvt<qcc::String> converter;
                converter.get((*propValue), val);
            }
            m_interfaceListener->OnUrlChanged(obj.GetPath(), val);
        } else if (s_prop_LifeRemaining == propNameStr) {
            uint8_t val;
            {
                CdmMsgCvt<uint8_t> converter;
                converter.get((*propValue), val);
            }
            m_interfaceListener->OnLifeRemainingChanged(obj.GetPath(), val);
        } else {
            QCC_DbgTrace(("Unknown property change signal received"));
        }
    }
}

//======================================================================
// Callbacks


void FilterStatusIntfController::Impl::GetExpectedLifeInDaysPropertyCB(QStatus status, ProxyBusObject* obj, const MsgArg& value, void* context)
{
    if (obj) {
        uint16_t val;
        {
            CdmMsgCvt<uint16_t> converter;
            converter.get(value, val);
        }
        if (_QCC_DbgPrintCheck(DBG_GEN_MESSAGE, QCC_MODULE)) {
            auto s = CdmMsgCvt<uint16_t>().str(value);
            QCC_DbgPrintf(("%s: received property %s=%s", __func__, "ExpectedLifeInDays", s.c_str()));
        }
        m_interfaceListener->OnResponseGetExpectedLifeInDays(status, obj->GetPath(), val, context);
    }
}




void FilterStatusIntfController::Impl::GetIsCleanablePropertyCB(QStatus status, ProxyBusObject* obj, const MsgArg& value, void* context)
{
    if (obj) {
        bool val;
        {
            CdmMsgCvt<bool> converter;
            converter.get(value, val);
        }
        if (_QCC_DbgPrintCheck(DBG_GEN_MESSAGE, QCC_MODULE)) {
            auto s = CdmMsgCvt<bool>().str(value);
            QCC_DbgPrintf(("%s: received property %s=%s", __func__, "IsCleanable", s.c_str()));
        }
        m_interfaceListener->OnResponseGetIsCleanable(status, obj->GetPath(), val, context);
    }
}




void FilterStatusIntfController::Impl::GetOrderPercentagePropertyCB(QStatus status, ProxyBusObject* obj, const MsgArg& value, void* context)
{
    if (obj) {
        uint8_t val;
        {
            CdmMsgCvt<uint8_t> converter;
            converter.get(value, val);
        }
        if (_QCC_DbgPrintCheck(DBG_GEN_MESSAGE, QCC_MODULE)) {
            auto s = CdmMsgCvt<uint8_t>().str(value);
            QCC_DbgPrintf(("%s: received property %s=%s", __func__, "OrderPercentage", s.c_str()));
        }
        m_interfaceListener->OnResponseGetOrderPercentage(status, obj->GetPath(), val, context);
    }
}




void FilterStatusIntfController::Impl::GetManufacturerPropertyCB(QStatus status, ProxyBusObject* obj, const MsgArg& value, void* context)
{
    if (obj) {
        qcc::String val;
        {
            CdmMsgCvt<qcc::String> converter;
            converter.get(value, val);
        }
        if (_QCC_DbgPrintCheck(DBG_GEN_MESSAGE, QCC_MODULE)) {
            auto s = CdmMsgCvt<qcc::String>().str(value);
            QCC_DbgPrintf(("%s: received property %s=%s", __func__, "Manufacturer", s.c_str()));
        }
        m_interfaceListener->OnResponseGetManufacturer(status, obj->GetPath(), val, context);
    }
}




void FilterStatusIntfController::Impl::GetPartNumberPropertyCB(QStatus status, ProxyBusObject* obj, const MsgArg& value, void* context)
{
    if (obj) {
        qcc::String val;
        {
            CdmMsgCvt<qcc::String> converter;
            converter.get(value, val);
        }
        if (_QCC_DbgPrintCheck(DBG_GEN_MESSAGE, QCC_MODULE)) {
            auto s = CdmMsgCvt<qcc::String>().str(value);
            QCC_DbgPrintf(("%s: received property %s=%s", __func__, "PartNumber", s.c_str()));
        }
        m_interfaceListener->OnResponseGetPartNumber(status, obj->GetPath(), val, context);
    }
}




void FilterStatusIntfController::Impl::GetUrlPropertyCB(QStatus status, ProxyBusObject* obj, const MsgArg& value, void* context)
{
    if (obj) {
        qcc::String val;
        {
            CdmMsgCvt<qcc::String> converter;
            converter.get(value, val);
        }
        if (_QCC_DbgPrintCheck(DBG_GEN_MESSAGE, QCC_MODULE)) {
            auto s = CdmMsgCvt<qcc::String>().str(value);
            QCC_DbgPrintf(("%s: received property %s=%s", __func__, "Url", s.c_str()));
        }
        m_interfaceListener->OnResponseGetUrl(status, obj->GetPath(), val, context);
    }
}




void FilterStatusIntfController::Impl::GetLifeRemainingPropertyCB(QStatus status, ProxyBusObject* obj, const MsgArg& value, void* context)
{
    if (obj) {
        uint8_t val;
        {
            CdmMsgCvt<uint8_t> converter;
            converter.get(value, val);
        }
        if (_QCC_DbgPrintCheck(DBG_GEN_MESSAGE, QCC_MODULE)) {
            auto s = CdmMsgCvt<uint8_t>().str(value);
            QCC_DbgPrintf(("%s: received property %s=%s", __func__, "LifeRemaining", s.c_str()));
        }
        m_interfaceListener->OnResponseGetLifeRemaining(status, obj->GetPath(), val, context);
    }
}




//======================================================================
// Forward to the impl

FilterStatusIntfController::FilterStatusIntfController(
    BusAttachment& busAttachment,
    Ref<InterfaceControllerListener> listener,
    Ref<ProxyBusObject> cdmProxyObject
    )
  : m_impl(new Impl(*this, busAttachment, dynamic_pointer_cast<FilterStatusIntfControllerListener>(listener), cdmProxyObject))
{
}



FilterStatusIntfController::~FilterStatusIntfController()
{
    delete m_impl;
}



Ref<CdmInterface> FilterStatusIntfController::CreateInterface(BusAttachment& busAttachment, Ref<InterfaceControllerListener> listener, Ref<ProxyBusObject> cdmProxyObject)
{
    return mkRef<FilterStatusIntfController>(busAttachment, dynamic_pointer_cast<FilterStatusIntfControllerListener>(listener), cdmProxyObject);
}



QStatus FilterStatusIntfController::Init()
{
    // Call the superclass Init
    QStatus status = CdmInterface::Init();
    if (ER_OK != status) {
        QCC_LogError(status, ("%s: Interface init failed.", __func__));
        return status;
    }

    return m_impl->Init();
}



BusAttachment& FilterStatusIntfController::GetBusAttachment() const
{
    return m_impl->m_busAttachment;
}



QStatus FilterStatusIntfController::GetExpectedLifeInDays(void* context)
{
    return m_impl->GetExpectedLifeInDays(context);
}



QStatus FilterStatusIntfController::GetIsCleanable(void* context)
{
    return m_impl->GetIsCleanable(context);
}



QStatus FilterStatusIntfController::GetOrderPercentage(void* context)
{
    return m_impl->GetOrderPercentage(context);
}



QStatus FilterStatusIntfController::GetManufacturer(void* context)
{
    return m_impl->GetManufacturer(context);
}



QStatus FilterStatusIntfController::GetPartNumber(void* context)
{
    return m_impl->GetPartNumber(context);
}



QStatus FilterStatusIntfController::GetUrl(void* context)
{
    return m_impl->GetUrl(context);
}



QStatus FilterStatusIntfController::GetLifeRemaining(void* context)
{
    return m_impl->GetLifeRemaining(context);
}

//======================================================================
} //namespace services
} //namespace ajn
