/******************************************************************************
 * Copyright (c) 2016 Open Connectivity Foundation (OCF) and AllJoyn Open
 *    Source Project (AJOSP) Contributors and others.
 *
 *    SPDX-License-Identifier: Apache-2.0
 *
 *    All rights reserved. This program and the accompanying materials are
 *    made available under the terms of the Apache License, Version 2.0
 *    which accompanies this distribution, and is available at
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 *    Copyright 2016 Open Connectivity Foundation and Contributors to
 *    AllSeen Alliance. All rights reserved.
 *
 *    Permission to use, copy, modify, and/or distribute this software for
 *    any purpose with or without fee is hereby granted, provided that the
 *    above copyright notice and this permission notice appear in all
 *    copies.
 *
 *     THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL
 *     WARRANTIES WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED
 *     WARRANTIES OF MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE
 *     AUTHOR BE LIABLE FOR ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL
 *     DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR
 *     PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER
 *     TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR
 *     PERFORMANCE OF THIS SOFTWARE.
 ******************************************************************************/

// This file is automatically generated. Do not edit it.

#include <alljoyn/cdm/common/LogModule.h>
#include <alljoyn/cdm/common/CdmTypes.h>
#include <alljoyn/cdm/controller/InterfaceController.h>
#include <interfaces/controller/operation/RapidModeTimedIntfControllerListener.h>
#include <interfaces/controller/operation/RapidModeTimedIntfController.h>

using namespace qcc;
using namespace std;

namespace ajn {
namespace services {
//======================================================================

typedef Ref<RapidModeTimedIntfControllerListener> MyInterfaceListener;


class RapidModeTimedIntfController::Impl : public InterfaceController
{
  public:

    Impl(
        RapidModeTimedIntfController& outer,
        BusAttachment& busAttachment,
        MyInterfaceListener listener,
        Ref<ProxyBusObject> proxyBusObject
        )
      : InterfaceController(proxyBusObject),
        m_outer(outer),
        m_busAttachment(busAttachment),
        m_interfaceListener(listener)
    {
    }

    QStatus Init();

    const char* GetInterfaceName() const
    {
        return m_outer.GetInterfaceName().c_str();
    }

    QStatus GetRapidModeMinutesRemaining(void* context);
    QStatus SetRapidModeMinutesRemaining(const uint16_t value, void* context);
    QStatus GetMaxSetMinutes(void* context);


    void PropertiesChanged(ProxyBusObject& obj, const char* ifaceName, const MsgArg& changed, const MsgArg& invalidated, void* context);

    void GetRapidModeMinutesRemainingPropertyCB(QStatus status, ProxyBusObject* obj, const MsgArg& value, void* context);
    void SetRapidModeMinutesRemainingPropertyCB(QStatus status, ProxyBusObject* obj, void* context);
    void GetMaxSetMinutesPropertyCB(QStatus status, ProxyBusObject* obj, const MsgArg& value, void* context);



    // The outer facet
    RapidModeTimedIntfController& m_outer;

    // and inherit m_proxyObject from InterfaceController
    BusAttachment& m_busAttachment;
    MyInterfaceListener m_interfaceListener;
};

//======================================================================

QStatus RapidModeTimedIntfController::Impl::Init()
{
    auto status = m_proxyObject->RegisterPropertiesChangedListener(GetInterfaceName(), NULL, 0, *this, NULL);

    if (ER_OK != status) {
        QCC_LogError(status, ("%s: RegisterPropertiesChangedListener failed.", __func__));
    }

    const InterfaceDescription* intf = m_outer.GetInterfaceDescription();
    if (intf) {
    } else {
        status = ER_FAIL;
        QCC_LogError(status, ("%s: The interface description does not exist.", __func__));
    }

    return status;
}




QStatus RapidModeTimedIntfController::Impl::GetRapidModeMinutesRemaining(void* context)
{
    auto status = m_proxyObject->GetPropertyAsync(GetInterfaceName(), s_prop_RapidModeMinutesRemaining.c_str(), this,
                (ProxyBusObject::Listener::GetPropertyCB)&RapidModeTimedIntfController::Impl::GetRapidModeMinutesRemainingPropertyCB, context);
    return status;
}

QStatus RapidModeTimedIntfController::Impl::SetRapidModeMinutesRemaining(const uint16_t value, void* context)
{
    MsgArg arg;
    {
        CdmMsgCvt<uint16_t> converter;
        converter.set(arg, value);
    }

    auto status = m_proxyObject->SetPropertyAsync(GetInterfaceName(), s_prop_RapidModeMinutesRemaining.c_str(), arg, this,
                (ProxyBusObject::Listener::SetPropertyCB)&RapidModeTimedIntfController::Impl::SetRapidModeMinutesRemainingPropertyCB, context);
    return status;
}

QStatus RapidModeTimedIntfController::Impl::GetMaxSetMinutes(void* context)
{
    auto status = m_proxyObject->GetPropertyAsync(GetInterfaceName(), s_prop_MaxSetMinutes.c_str(), this,
                (ProxyBusObject::Listener::GetPropertyCB)&RapidModeTimedIntfController::Impl::GetMaxSetMinutesPropertyCB, context);
    return status;
}





void RapidModeTimedIntfController::Impl::PropertiesChanged(ProxyBusObject& obj, const char* ifaceName, const MsgArg& changed, const MsgArg& invalidated, void* context)
{
    MsgArg* entries;
    size_t numEntries;

    changed.Get("a{sv}", &numEntries, &entries);
    for (size_t i = 0; i < numEntries; ++i) {
        const char* propName;
        MsgArg* propValue;
        entries[i].Get("{sv}", &propName, &propValue);
        String propNameStr(propName);

        if (s_prop_RapidModeMinutesRemaining == propNameStr) {
            uint16_t val;
            {
                CdmMsgCvt<uint16_t> converter;
                converter.get((*propValue), val);
            }
            m_interfaceListener->OnRapidModeMinutesRemainingChanged(obj.GetPath(), val);
        } else if (s_prop_MaxSetMinutes == propNameStr) {
            uint16_t val;
            {
                CdmMsgCvt<uint16_t> converter;
                converter.get((*propValue), val);
            }
            m_interfaceListener->OnMaxSetMinutesChanged(obj.GetPath(), val);
        } else {
            QCC_DbgTrace(("Unknown property change signal received"));
        }
    }
}

//======================================================================
// Callbacks


void RapidModeTimedIntfController::Impl::GetRapidModeMinutesRemainingPropertyCB(QStatus status, ProxyBusObject* obj, const MsgArg& value, void* context)
{
    if (obj) {
        uint16_t val;
        {
            CdmMsgCvt<uint16_t> converter;
            converter.get(value, val);
        }
        if (_QCC_DbgPrintCheck(DBG_GEN_MESSAGE, QCC_MODULE)) {
            auto s = CdmMsgCvt<uint16_t>().str(value);
            QCC_DbgPrintf(("%s: received property %s=%s", __func__, "RapidModeMinutesRemaining", s.c_str()));
        }
        m_interfaceListener->OnResponseGetRapidModeMinutesRemaining(status, obj->GetPath(), val, context);
    }
}



void RapidModeTimedIntfController::Impl::SetRapidModeMinutesRemainingPropertyCB(QStatus status, ProxyBusObject* obj, void* context)
{
    QCC_DbgPrintf(("%s: set completed", __func__));
    if (obj) {
        m_interfaceListener->OnResponseSetRapidModeMinutesRemaining(status, obj->GetPath(), context);
    }
}

void RapidModeTimedIntfController::Impl::GetMaxSetMinutesPropertyCB(QStatus status, ProxyBusObject* obj, const MsgArg& value, void* context)
{
    if (obj) {
        uint16_t val;
        {
            CdmMsgCvt<uint16_t> converter;
            converter.get(value, val);
        }
        if (_QCC_DbgPrintCheck(DBG_GEN_MESSAGE, QCC_MODULE)) {
            auto s = CdmMsgCvt<uint16_t>().str(value);
            QCC_DbgPrintf(("%s: received property %s=%s", __func__, "MaxSetMinutes", s.c_str()));
        }
        m_interfaceListener->OnResponseGetMaxSetMinutes(status, obj->GetPath(), val, context);
    }
}




//======================================================================
// Forward to the impl

RapidModeTimedIntfController::RapidModeTimedIntfController(
    BusAttachment& busAttachment,
    Ref<InterfaceControllerListener> listener,
    Ref<ProxyBusObject> cdmProxyObject
    )
  : m_impl(new Impl(*this, busAttachment, dynamic_pointer_cast<RapidModeTimedIntfControllerListener>(listener), cdmProxyObject))
{
}



RapidModeTimedIntfController::~RapidModeTimedIntfController()
{
    delete m_impl;
}



Ref<CdmInterface> RapidModeTimedIntfController::CreateInterface(BusAttachment& busAttachment, Ref<InterfaceControllerListener> listener, Ref<ProxyBusObject> cdmProxyObject)
{
    return mkRef<RapidModeTimedIntfController>(busAttachment, dynamic_pointer_cast<RapidModeTimedIntfControllerListener>(listener), cdmProxyObject);
}



QStatus RapidModeTimedIntfController::Init()
{
    // Call the superclass Init
    QStatus status = CdmInterface::Init();
    if (ER_OK != status) {
        QCC_LogError(status, ("%s: Interface init failed.", __func__));
        return status;
    }

    return m_impl->Init();
}



BusAttachment& RapidModeTimedIntfController::GetBusAttachment() const
{
    return m_impl->m_busAttachment;
}



QStatus RapidModeTimedIntfController::GetRapidModeMinutesRemaining(void* context)
{
    return m_impl->GetRapidModeMinutesRemaining(context);
}



QStatus RapidModeTimedIntfController::SetRapidModeMinutesRemaining(const uint16_t value, void* context)
{
    return m_impl->SetRapidModeMinutesRemaining(value, context);
}



QStatus RapidModeTimedIntfController::GetMaxSetMinutes(void* context)
{
    return m_impl->GetMaxSetMinutes(context);
}

//======================================================================
} //namespace services
} //namespace ajn