/******************************************************************************
 *  * Copyright (c) Open Connectivity Foundation (OCF) and AllJoyn Open
 *    Source Project (AJOSP) Contributors and others.
 *
 *    SPDX-License-Identifier: Apache-2.0
 *
 *    All rights reserved. This program and the accompanying materials are
 *    made available under the terms of the Apache License, Version 2.0
 *    which accompanies this distribution, and is available at
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 *    Copyright (c) Open Connectivity Foundation and Contributors to AllSeen
 *    Alliance. All rights reserved.
 *
 *    Permission to use, copy, modify, and/or distribute this software for
 *    any purpose with or without fee is hereby granted, provided that the
 *    above copyright notice and this permission notice appear in all
 *    copies.
 *
 *     THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL
 *     WARRANTIES WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED
 *     WARRANTIES OF MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE
 *     AUTHOR BE LIABLE FOR ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL
 *     DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR
 *     PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER
 *     TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR
 *     PERFORMANCE OF THIS SOFTWARE.
 ******************************************************************************/

// This file is automatically generated. Do not edit it.

#include <alljoyn/cdm/common/LogModule.h>
#include <alljoyn/cdm/common/CdmTypes.h>
#include <alljoyn/cdm/controller/InterfaceController.h>
#include <interfaces/controller/operation/TimerIntfControllerListener.h>
#include <interfaces/controller/operation/TimerIntfController.h>

using namespace qcc;
using namespace std;

namespace ajn {
namespace services {
//======================================================================

typedef Ref<TimerIntfControllerListener> MyInterfaceListener;


class TimerIntfController::Impl : public InterfaceController
{
  public:

    Impl(
        TimerIntfController& outer,
        BusAttachment& busAttachment,
        MyInterfaceListener listener,
        Ref<ProxyBusObject> proxyBusObject
        )
      : InterfaceController(proxyBusObject),
        m_outer(outer),
        m_busAttachment(busAttachment),
        m_interfaceListener(listener)
    {
    }

    QStatus Init();

    const char* GetInterfaceName() const
    {
        return m_outer.GetInterfaceName().c_str();
    }

    QStatus GetReferenceTimer(void* context);
    QStatus GetTargetTimeToStart(void* context);
    QStatus GetTargetTimeToStop(void* context);
    QStatus GetEstimatedTimeToEnd(void* context);
    QStatus GetRunningTime(void* context);
    QStatus GetTargetDuration(void* context);

    virtual QStatus SetTargetTimeToStart(const int32_t targetTimeToStart, void* context);
    virtual QStatus SetTargetTimeToStop(const int32_t targetTimeToStop, void* context);

    void PropertiesChanged(ProxyBusObject& obj, const char* ifaceName, const MsgArg& changed, const MsgArg& invalidated, void* context);

    void GetReferenceTimerPropertyCB(QStatus status, ProxyBusObject* obj, const MsgArg& value, void* context);
    void GetTargetTimeToStartPropertyCB(QStatus status, ProxyBusObject* obj, const MsgArg& value, void* context);
    void GetTargetTimeToStopPropertyCB(QStatus status, ProxyBusObject* obj, const MsgArg& value, void* context);
    void GetEstimatedTimeToEndPropertyCB(QStatus status, ProxyBusObject* obj, const MsgArg& value, void* context);
    void GetRunningTimePropertyCB(QStatus status, ProxyBusObject* obj, const MsgArg& value, void* context);
    void GetTargetDurationPropertyCB(QStatus status, ProxyBusObject* obj, const MsgArg& value, void* context);

    void SetTargetTimeToStartReplyHandler(Message& message, void* context);
    void SetTargetTimeToStopReplyHandler(Message& message, void* context);


    // The outer facet
    TimerIntfController& m_outer;

    // and inherit m_proxyObject from InterfaceController
    BusAttachment& m_busAttachment;
    MyInterfaceListener m_interfaceListener;
};

//======================================================================

QStatus TimerIntfController::Impl::Init()
{
    auto status = m_proxyObject->RegisterPropertiesChangedListener(GetInterfaceName(), NULL, 0, *this, NULL);

    if (ER_OK != status) {
        QCC_LogError(status, ("%s: RegisterPropertiesChangedListener failed.", __func__));
    }

    const InterfaceDescription* intf = m_outer.GetInterfaceDescription();
    if (intf) {
    } else {
        status = ER_FAIL;
        QCC_LogError(status, ("%s: The interface description does not exist.", __func__));
    }

    return status;
}




QStatus TimerIntfController::Impl::GetReferenceTimer(void* context)
{
    auto status = m_proxyObject->GetPropertyAsync(GetInterfaceName(), s_prop_ReferenceTimer.c_str(), this,
                (ProxyBusObject::Listener::GetPropertyCB)&TimerIntfController::Impl::GetReferenceTimerPropertyCB, context);
    return status;
}

QStatus TimerIntfController::Impl::GetTargetTimeToStart(void* context)
{
    auto status = m_proxyObject->GetPropertyAsync(GetInterfaceName(), s_prop_TargetTimeToStart.c_str(), this,
                (ProxyBusObject::Listener::GetPropertyCB)&TimerIntfController::Impl::GetTargetTimeToStartPropertyCB, context);
    return status;
}

QStatus TimerIntfController::Impl::GetTargetTimeToStop(void* context)
{
    auto status = m_proxyObject->GetPropertyAsync(GetInterfaceName(), s_prop_TargetTimeToStop.c_str(), this,
                (ProxyBusObject::Listener::GetPropertyCB)&TimerIntfController::Impl::GetTargetTimeToStopPropertyCB, context);
    return status;
}

QStatus TimerIntfController::Impl::GetEstimatedTimeToEnd(void* context)
{
    auto status = m_proxyObject->GetPropertyAsync(GetInterfaceName(), s_prop_EstimatedTimeToEnd.c_str(), this,
                (ProxyBusObject::Listener::GetPropertyCB)&TimerIntfController::Impl::GetEstimatedTimeToEndPropertyCB, context);
    return status;
}

QStatus TimerIntfController::Impl::GetRunningTime(void* context)
{
    auto status = m_proxyObject->GetPropertyAsync(GetInterfaceName(), s_prop_RunningTime.c_str(), this,
                (ProxyBusObject::Listener::GetPropertyCB)&TimerIntfController::Impl::GetRunningTimePropertyCB, context);
    return status;
}

QStatus TimerIntfController::Impl::GetTargetDuration(void* context)
{
    auto status = m_proxyObject->GetPropertyAsync(GetInterfaceName(), s_prop_TargetDuration.c_str(), this,
                (ProxyBusObject::Listener::GetPropertyCB)&TimerIntfController::Impl::GetTargetDurationPropertyCB, context);
    return status;
}



QStatus TimerIntfController::Impl::SetTargetTimeToStart(const int32_t targetTimeToStart, void* context)
{
    // Method call
    static const size_t numInputs = 1;
    MsgArg args[numInputs];

    {
        CdmMsgCvt<int32_t> converter;
        converter.set(args[0], targetTimeToStart);
    }

    auto status = m_proxyObject->MethodCallAsync(GetInterfaceName(), s_method_SetTargetTimeToStart.c_str(), this,
                (MessageReceiver::ReplyHandler)&TimerIntfController::Impl::SetTargetTimeToStartReplyHandler,
                args, numInputs, context);
    return status;
}

QStatus TimerIntfController::Impl::SetTargetTimeToStop(const int32_t targetTimeToStop, void* context)
{
    // Method call
    static const size_t numInputs = 1;
    MsgArg args[numInputs];

    {
        CdmMsgCvt<int32_t> converter;
        converter.set(args[0], targetTimeToStop);
    }

    auto status = m_proxyObject->MethodCallAsync(GetInterfaceName(), s_method_SetTargetTimeToStop.c_str(), this,
                (MessageReceiver::ReplyHandler)&TimerIntfController::Impl::SetTargetTimeToStopReplyHandler,
                args, numInputs, context);
    return status;
}



void TimerIntfController::Impl::PropertiesChanged(ProxyBusObject& obj, const char* ifaceName, const MsgArg& changed, const MsgArg& invalidated, void* context)
{
    MsgArg* entries;
    size_t numEntries;

    changed.Get("a{sv}", &numEntries, &entries);
    for (size_t i = 0; i < numEntries; ++i) {
        const char* propName;
        MsgArg* propValue;
        entries[i].Get("{sv}", &propName, &propValue);
        String propNameStr(propName);

        if (s_prop_ReferenceTimer == propNameStr) {
            int32_t val;
            {
                CdmMsgCvt<int32_t> converter;
                converter.get((*propValue), val);
            }
            m_interfaceListener->OnReferenceTimerChanged(obj.GetPath(), val);
        } else if (s_prop_TargetTimeToStart == propNameStr) {
            int32_t val;
            {
                CdmMsgCvt<int32_t> converter;
                converter.get((*propValue), val);
            }
            m_interfaceListener->OnTargetTimeToStartChanged(obj.GetPath(), val);
        } else if (s_prop_TargetTimeToStop == propNameStr) {
            int32_t val;
            {
                CdmMsgCvt<int32_t> converter;
                converter.get((*propValue), val);
            }
            m_interfaceListener->OnTargetTimeToStopChanged(obj.GetPath(), val);
        } else if (s_prop_EstimatedTimeToEnd == propNameStr) {
            int32_t val;
            {
                CdmMsgCvt<int32_t> converter;
                converter.get((*propValue), val);
            }
            m_interfaceListener->OnEstimatedTimeToEndChanged(obj.GetPath(), val);
        } else if (s_prop_RunningTime == propNameStr) {
            int32_t val;
            {
                CdmMsgCvt<int32_t> converter;
                converter.get((*propValue), val);
            }
            m_interfaceListener->OnRunningTimeChanged(obj.GetPath(), val);
        } else if (s_prop_TargetDuration == propNameStr) {
            int32_t val;
            {
                CdmMsgCvt<int32_t> converter;
                converter.get((*propValue), val);
            }
            m_interfaceListener->OnTargetDurationChanged(obj.GetPath(), val);
        } else {
            QCC_DbgTrace(("Unknown property change signal received"));
        }
    }
}

//======================================================================
// Callbacks


void TimerIntfController::Impl::GetReferenceTimerPropertyCB(QStatus status, ProxyBusObject* obj, const MsgArg& value, void* context)
{
    if (obj) {
        int32_t val;
        {
            CdmMsgCvt<int32_t> converter;
            converter.get(value, val);
        }
        if (_QCC_DbgPrintCheck(DBG_GEN_MESSAGE, QCC_MODULE)) {
            auto s = CdmMsgCvt<int32_t>().str(value);
            QCC_DbgPrintf(("%s: received property %s=%s", __func__, "ReferenceTimer", s.c_str()));
        }
        m_interfaceListener->OnResponseGetReferenceTimer(status, obj->GetPath(), val, context);
    }
}




void TimerIntfController::Impl::GetTargetTimeToStartPropertyCB(QStatus status, ProxyBusObject* obj, const MsgArg& value, void* context)
{
    if (obj) {
        int32_t val;
        {
            CdmMsgCvt<int32_t> converter;
            converter.get(value, val);
        }
        if (_QCC_DbgPrintCheck(DBG_GEN_MESSAGE, QCC_MODULE)) {
            auto s = CdmMsgCvt<int32_t>().str(value);
            QCC_DbgPrintf(("%s: received property %s=%s", __func__, "TargetTimeToStart", s.c_str()));
        }
        m_interfaceListener->OnResponseGetTargetTimeToStart(status, obj->GetPath(), val, context);
    }
}




void TimerIntfController::Impl::GetTargetTimeToStopPropertyCB(QStatus status, ProxyBusObject* obj, const MsgArg& value, void* context)
{
    if (obj) {
        int32_t val;
        {
            CdmMsgCvt<int32_t> converter;
            converter.get(value, val);
        }
        if (_QCC_DbgPrintCheck(DBG_GEN_MESSAGE, QCC_MODULE)) {
            auto s = CdmMsgCvt<int32_t>().str(value);
            QCC_DbgPrintf(("%s: received property %s=%s", __func__, "TargetTimeToStop", s.c_str()));
        }
        m_interfaceListener->OnResponseGetTargetTimeToStop(status, obj->GetPath(), val, context);
    }
}




void TimerIntfController::Impl::GetEstimatedTimeToEndPropertyCB(QStatus status, ProxyBusObject* obj, const MsgArg& value, void* context)
{
    if (obj) {
        int32_t val;
        {
            CdmMsgCvt<int32_t> converter;
            converter.get(value, val);
        }
        if (_QCC_DbgPrintCheck(DBG_GEN_MESSAGE, QCC_MODULE)) {
            auto s = CdmMsgCvt<int32_t>().str(value);
            QCC_DbgPrintf(("%s: received property %s=%s", __func__, "EstimatedTimeToEnd", s.c_str()));
        }
        m_interfaceListener->OnResponseGetEstimatedTimeToEnd(status, obj->GetPath(), val, context);
    }
}




void TimerIntfController::Impl::GetRunningTimePropertyCB(QStatus status, ProxyBusObject* obj, const MsgArg& value, void* context)
{
    if (obj) {
        int32_t val;
        {
            CdmMsgCvt<int32_t> converter;
            converter.get(value, val);
        }
        if (_QCC_DbgPrintCheck(DBG_GEN_MESSAGE, QCC_MODULE)) {
            auto s = CdmMsgCvt<int32_t>().str(value);
            QCC_DbgPrintf(("%s: received property %s=%s", __func__, "RunningTime", s.c_str()));
        }
        m_interfaceListener->OnResponseGetRunningTime(status, obj->GetPath(), val, context);
    }
}




void TimerIntfController::Impl::GetTargetDurationPropertyCB(QStatus status, ProxyBusObject* obj, const MsgArg& value, void* context)
{
    if (obj) {
        int32_t val;
        {
            CdmMsgCvt<int32_t> converter;
            converter.get(value, val);
        }
        if (_QCC_DbgPrintCheck(DBG_GEN_MESSAGE, QCC_MODULE)) {
            auto s = CdmMsgCvt<int32_t>().str(value);
            QCC_DbgPrintf(("%s: received property %s=%s", __func__, "TargetDuration", s.c_str()));
        }
        m_interfaceListener->OnResponseGetTargetDuration(status, obj->GetPath(), val, context);
    }
}






void TimerIntfController::Impl::SetTargetTimeToStartReplyHandler(Message& message, void* context)
{
    qcc::String errorMessage;
    const char* errorName = message->GetErrorName(&errorMessage);
    QStatus status = ER_OK;
    size_t numArgs = 0;
    const MsgArg* args = 0;


    if (message->GetType() == MESSAGE_METHOD_RET) {
        message->GetArgs(numArgs, args);
    } else {
        status = ER_FAIL;
    }

    m_interfaceListener->OnResponseSetTargetTimeToStart(status, m_proxyObject->GetPath(), context, errorName, errorMessage.c_str());
}



void TimerIntfController::Impl::SetTargetTimeToStopReplyHandler(Message& message, void* context)
{
    qcc::String errorMessage;
    const char* errorName = message->GetErrorName(&errorMessage);
    QStatus status = ER_OK;
    size_t numArgs = 0;
    const MsgArg* args = 0;


    if (message->GetType() == MESSAGE_METHOD_RET) {
        message->GetArgs(numArgs, args);
    } else {
        status = ER_FAIL;
    }

    m_interfaceListener->OnResponseSetTargetTimeToStop(status, m_proxyObject->GetPath(), context, errorName, errorMessage.c_str());
}

//======================================================================
// Forward to the impl

TimerIntfController::TimerIntfController(
    BusAttachment& busAttachment,
    Ref<InterfaceControllerListener> listener,
    Ref<ProxyBusObject> cdmProxyObject
    )
  : m_impl(new Impl(*this, busAttachment, dynamic_pointer_cast<TimerIntfControllerListener>(listener), cdmProxyObject))
{
}



TimerIntfController::~TimerIntfController()
{
    delete m_impl;
}



Ref<CdmInterface> TimerIntfController::CreateInterface(BusAttachment& busAttachment, Ref<InterfaceControllerListener> listener, Ref<ProxyBusObject> cdmProxyObject)
{
    return mkRef<TimerIntfController>(busAttachment, dynamic_pointer_cast<TimerIntfControllerListener>(listener), cdmProxyObject);
}



QStatus TimerIntfController::Init()
{
    // Call the superclass Init
    QStatus status = CdmInterface::Init();
    if (ER_OK != status) {
        QCC_LogError(status, ("%s: Interface init failed.", __func__));
        return status;
    }

    return m_impl->Init();
}



BusAttachment& TimerIntfController::GetBusAttachment() const
{
    return m_impl->m_busAttachment;
}



QStatus TimerIntfController::GetReferenceTimer(void* context)
{
    return m_impl->GetReferenceTimer(context);
}



QStatus TimerIntfController::GetTargetTimeToStart(void* context)
{
    return m_impl->GetTargetTimeToStart(context);
}



QStatus TimerIntfController::GetTargetTimeToStop(void* context)
{
    return m_impl->GetTargetTimeToStop(context);
}



QStatus TimerIntfController::GetEstimatedTimeToEnd(void* context)
{
    return m_impl->GetEstimatedTimeToEnd(context);
}



QStatus TimerIntfController::GetRunningTime(void* context)
{
    return m_impl->GetRunningTime(context);
}



QStatus TimerIntfController::GetTargetDuration(void* context)
{
    return m_impl->GetTargetDuration(context);
}



QStatus TimerIntfController::SetTargetTimeToStart(const int32_t targetTimeToStart, void* context)
{
    return m_impl->SetTargetTimeToStart(targetTimeToStart, context);
}



QStatus TimerIntfController::SetTargetTimeToStop(const int32_t targetTimeToStop, void* context)
{
    return m_impl->SetTargetTimeToStop(targetTimeToStop, context);
}

//======================================================================
} //namespace services
} //namespace ajn