# # 
#    Copyright (c) 2016 Open Connectivity Foundation and AllJoyn Open
#    Source Project Contributors and others.
#    
#    All rights reserved. This program and the accompanying materials are
#    made available under the terms of the Apache License, Version 2.0
#    which accompanies this distribution, and is available at
#    http://www.apache.org/licenses/LICENSE-2.0


Import('env')

env.Append(CPPPATH = '../BaseSample');
env.Append(CPPPATH = '../BaseSample/Controller');
env.Append(CPPPATH = '../BaseSample/VendorDefinedInterfaces');

srcs = env.Glob('*.cc')
srcs += env.Glob('../BaseSample/*.cc')
srcs += env.Glob('../BaseSample/Controller/*.cc')
srcs += env.Glob('../BaseSample/VendorDefinedInterfaces/*.cc')

objs = env.Object(srcs)

prog = env.Program('IntegratedController', objs)

Return('prog')