/******************************************************************************
 * Copyright (c) Open Connectivity Foundation (OCF) and AllJoyn Open
 *    Source Project (AJOSP) Contributors and others.
 *
 *    SPDX-License-Identifier: Apache-2.0
 *
 *    All rights reserved. This program and the accompanying materials are
 *    made available under the terms of the Apache License, Version 2.0
 *    which accompanies this distribution, and is available at
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 *    Copyright (c) Open Connectivity Foundation and Contributors to AllSeen
 *    Alliance. All rights reserved.
 *
 *    Permission to use, copy, modify, and/or distribute this software for
 *    any purpose with or without fee is hereby granted, provided that the
 *    above copyright notice and this permission notice appear in all
 *    copies.
 *
 *     THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL
 *     WARRANTIES WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED
 *     WARRANTIES OF MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE
 *     AUTHOR BE LIABLE FOR ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL
 *     DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR
 *     PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER
 *     TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR
 *     PERFORMANCE OF THIS SOFTWARE.
 ******************************************************************************/

// This file is automatically generated. Do not edit it.

#include <alljoyn/cdm/common/LogModule.h>
#include <interfaces/common/operation/CycleControlInterface.h>

namespace ajn {
namespace services {

const char* const CycleControlInterface::INTERFACE_NAME = "org.alljoyn.SmartSpaces.Operation.CycleControl";
const CdmInterfaceType CycleControlInterface::INTERFACE_TYPE = CYCLE_CONTROL_INTERFACE;


const uint16_t CycleControlInterface::s_interfaceVersion = 1;

const qcc::String CycleControlInterface::s_xml =
"<node xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance' xsi:noNamespaceSchemaLocation='http://www.allseenalliance.org/schemas/introspect.xsd'>"
"    <interface name='org.alljoyn.SmartSpaces.Operation.CycleControl'>"
"        <annotation name='org.alljoyn.Bus.DocString.En' value='This interface provides capability to monitor the operational state of an appliance and to control it using relate commands.'/>"
"        <annotation name='org.alljoyn.Bus.Secure' value='true'/>"
"        <property name='Version' type='q' access='read'>"
"            <annotation name='org.alljoyn.Bus.DocString.En' value='The interface version.'/>"
"            <annotation name='org.freedesktop.DBus.Property.EmitsChangedSignal' value='const'/>"
"        </property>"
"        <annotation name='org.alljoyn.Bus.Enum.OperationalState.Value.Idle' value='0'/>"
"        <annotation name='org.alljoyn.Bus.Enum.OperationalState.Value.Working' value='1'/>"
"        <annotation name='org.alljoyn.Bus.Enum.OperationalState.Value.ReadyToStart' value='2'/>"
"        <annotation name='org.alljoyn.Bus.Enum.OperationalState.Value.DelayedStart' value='3'/>"
"        <annotation name='org.alljoyn.Bus.Enum.OperationalState.Value.Paused' value='4'/>"
"        <annotation name='org.alljoyn.Bus.Enum.OperationalState.Value.EndOfCycle' value='5'/>"
"        <property name='OperationalState' type='y' access='read'>"
"            <annotation name='org.alljoyn.Bus.DocString.En' value='Current operational state of the appliance.'/>"
"            <annotation name='org.alljoyn.Bus.Type.Name' value='[OperationalState]'/>"
"            <annotation name='org.freedesktop.DBus.Property.EmitsChangedSignal' value='true'/>"
"        </property>"
"        <property name='SupportedOperationalStates' type='ay' access='read'>"
"            <annotation name='org.alljoyn.Bus.DocString.En' value='Operational states which are supported by the appliance.'/>"
"            <annotation name='org.alljoyn.Bus.Type.Name' value='a[OperationalState]'/>"
"            <annotation name='org.freedesktop.DBus.Property.EmitsChangedSignal' value='const'/>"
"        </property>"
"        <annotation name='org.alljoyn.Bus.Enum.OperationalCommands.Value.Start' value='0'/>"
"        <annotation name='org.alljoyn.Bus.Enum.OperationalCommands.Value.Stop' value='1'/>"
"        <annotation name='org.alljoyn.Bus.Enum.OperationalCommands.Value.Pause' value='2'/>"
"        <annotation name='org.alljoyn.Bus.Enum.OperationalCommands.Value.Resume' value='3'/>"
"        <property name='SupportedOperationalCommands' type='ay' access='read'>"
"            <annotation name='org.alljoyn.Bus.DocString.En' value='Operational commands which are supported by the appliance.'/>"
"            <annotation name='org.alljoyn.Bus.Type.Name' value='a[OperationalCommands]'/>"
"            <annotation name='org.freedesktop.DBus.Property.EmitsChangedSignal' value='const'/>"
"        </property>"
"        <method name='ExecuteOperationalCommand'>"
"            <annotation name='org.alljoyn.Bus.DocString.En' value='Execute an operational command.'/>"
"            <arg name='command' type='y' direction='in'>"
"                <annotation name='org.alljoyn.Bus.DocString.En' value='Operational command to be executed.'/>"
"                <annotation name='org.alljoyn.Bus.Type.Name' value='[OperationalCommands]'/>"
"            </arg>"
"        </method>"
"    </interface>"
"</node>"
;

const qcc::String CycleControlInterface::s_prop_Version = "Version";
const qcc::String CycleControlInterface::s_prop_OperationalState = "OperationalState";
const qcc::String CycleControlInterface::s_prop_SupportedOperationalStates = "SupportedOperationalStates";
const qcc::String CycleControlInterface::s_prop_SupportedOperationalCommands = "SupportedOperationalCommands";
const qcc::String CycleControlInterface::s_method_ExecuteOperationalCommand = "ExecuteOperationalCommand";

} //namespace services
} //namespace ajn