/******************************************************************************
 * Copyright (c) 2013-2014, AllSeen Alliance. All rights reserved.
 *
 *    Permission to use, copy, modify, and/or distribute this software for any
 *    purpose with or without fee is hereby granted, provided that the above
 *    copyright notice and this permission notice appear in all copies.
 *
 *    THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
 *    WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
 *    MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
 *    ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
 *    WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
 *    ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
 *    OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
 ******************************************************************************/

// This file is automatically generated. Do not edit it.

#include <alljoyn/cdm/common/LogModule.h>
#include <interfaces/common/environment/CurrentHumidityInterface.h>

namespace ajn {
namespace services {

const char* const CurrentHumidityInterface::INTERFACE_NAME = "org.alljoyn.SmartSpaces.Environment.CurrentHumidity";
const CdmInterfaceType CurrentHumidityInterface::INTERFACE_TYPE = CURRENT_HUMIDITY_INTERFACE;


const uint16_t CurrentHumidityInterface::s_interfaceVersion = 1;

const qcc::String CurrentHumidityInterface::s_xml =
"<node xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance' xmlns='http://www.allseenalliance.org/schemas/introspect' xsi:schemaLocation='http://www.allseenalliance.org/schemas/introspect.xsd'>"
"    <interface name='org.alljoyn.SmartSpaces.Environment.CurrentHumidity'>"
"        <annotation name='org.alljoyn.Bus.DocString.En' value='This interface provides capability to represent current relative humidity.'/>"
"        <annotation name='org.alljoyn.Bus.Secure' value='true'/>"
"        <property name='Version' type='q' access='read'>"
"            <annotation name='org.alljoyn.Bus.DocString.En' value='The interface version'/>"
"            <annotation name='org.freedesktop.DBus.Property.EmitsChangedSignal' value='const'/>"
"        </property>"
"        <property name='CurrentValue' type='y' access='read'>"
"            <annotation name='org.alljoyn.Bus.DocString.En' value='Current relative humidity value'/>"
"            <annotation name='org.freedesktop.DBus.Property.EmitsChangedSignal' value='true'/>"
"            <annotation name='org.alljoyn.Bus.Type.Min' value='0'/>"
"        </property>"
"        <property name='MaxValue' type='y' access='read'>"
"            <annotation name='org.alljoyn.Bus.DocString.En' value='Maximum value allowed for represented relative humidity'/>"
"            <annotation name='org.freedesktop.DBus.Property.EmitsChangedSignal' value='true'/>"
"        </property>"
"    </interface>"
"</node>"
;

const qcc::String CurrentHumidityInterface::s_prop_Version = "Version";
const qcc::String CurrentHumidityInterface::s_prop_CurrentValue = "CurrentValue";
const qcc::String CurrentHumidityInterface::s_prop_MaxValue = "MaxValue";

} //namespace services
} //namespace ajn
